### ISSUE TITLE
Gmail网页版下，无法选择翻译的源语言和目标语言

### ISSUE THREAD

**Issue by Mjmaster** [yetone/openai-translator#10]
Gmail网页版下，无法选择翻译的源语言和目标语言

**Comment by yetone** [comment]
你好，最新版 [0.0.4](https://github.com/yetone/openai-translator/releases/tag/v0.0.4) 已经解决这个问题

**Comment by Mjmaster** [comment]
试了0.0.4，已修复，谢谢！
