### ISSUE TITLE
[BUG] 拖动工具窗口后无法释放

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#100]
环境：Chrome 111(正式版），win11-pro-22H2，openai-translator v0.0.14
触发前提：工具窗口**部分处在屏幕外**
触发过程：左键长按工具窗口完全拖动至屏幕内然后释放
结果：释放后，工具窗口继续跟随指针**持续移动**

**临时**解决方案：此时直接右键鼠标，工具窗口原地停下，将鼠标移至窗口左上角**标题栏**左键单击一次，窗口不再跟随鼠标

比较神奇的 bug 哈哈！

**Comment by syt-honey** [comment]
我也遇到了同样的问题，窗口一直跟着指针，无法释放

**Comment by syt-honey** [comment]
> 我也遇到了同样的问题，窗口一直跟着指针，无法释放

环境：Chrome 110.0.5481.177（正式版本） (x86_64)、MacOS Ventura 13.0、openAI v0.0.14

**Comment by syt-honey** [comment]
> > 我也遇到了同样的问题，窗口一直跟着指针，无法释放
> 
> 环境：Chrome 110.0.5481.177（正式版本） (x86_64)、MacOS Ventura 13.0、openAI v0.0.14

已解决：

在面板中将 `Auto` 的勾选去掉即可。

<img width="378" alt="image" src="https://user-images.githubusercontent.com/36325249/223917298-5cef0f8a-5712-4c3d-94cd-07ab4646b9bb.png">

**Comment by szh-bash** [comment]
> > > 我也遇到了同样的问题，窗口一直跟着指针，无法释放
> > 
> > 
> > 环境：Chrome 110.0.5481.177（正式版本） (x86_64)、MacOS Ventura 13.0、openAI v0.0.14
> 
> 已解决：
> 
> 在面板中将 `Auto` 的勾选去掉即可。
> 
> <img alt="image" width="378" src="https://user-images.githubusercontent.com/36325249/223917298-5cef0f8a-5712-4c3d-94cd-07ab4646b9bb.png">
> 
> 哈喽，你看下和我的问题一不一样，可以参考一下 @szh-bash

这个方法在我地方不适用。你试试手动把窗口的一部分拖到屏幕外**释放后**再拉回来，应该 100% 会无法释放

**Comment by szh-bash** [comment]
重新开了 issue #181
