### ISSUE TITLE
MacApp包体疑似损坏

### ISSUE THREAD

**Issue by nangcr** [yetone/openai-translator#102]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/9512549/223903597-c8a9a791-dc2f-48f5-8517-c5e3e893d428.png">
<img width="194" alt="image" src="https://user-images.githubusercontent.com/9512549/223903731-643bac21-74a4-4048-88c4-83a2f64fc20e.png">

**Comment by wyg-lucas** [comment]
俺也是，遇到了一样的问题

**Comment by Wjshang** [comment]
+1

**Comment by zengjunjie1026** [comment]
+1

**Comment by Muscleape** [comment]
提示开发者不受信任，这个配置是可以的，但是现在提示的信息是文件受损，Open Anyway选项就不会出来了

**Comment by yetone** [comment]
这是正常现象，所有未经 Apple 官方 AppStore 发布的应用都会有这个提示，请按照我写的安装文档进行操作：https://github.com/yetone/openai-translator#%E6%A1%8C%E9%9D%A2%E5%BA%94%E7%94%A8%E7%89%88%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by Muscleape** [comment]
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/9512549/223903597-c8a9a791-dc2f-48f5-8517-c5e3e893d428.png">
> 
> <img alt="image" width="194" src="https://user-images.githubusercontent.com/9512549/223903731-643bac21-74a4-4048-88c4-83a2f64fc20e.png">

正确的处理方式

sudo xattr -rd com.apple.quarantine /Applications/OpenAI\ Translator.app
