### ISSUE TITLE
Bug 单击浏览器页面时也会弹窗

### ISSUE THREAD

**Issue by devyujie** [yetone/openai-translator#113]
浏览器插件在鼠标单击浏览器页面时也会弹窗，此时并没有选中任何文本

**Comment by szh-bash** [comment]
我这好像不会，有更详细的复现方式吗

**Comment by devyujie** [comment]
没勾也会这样

**Comment by bombready** [comment]
我之前也遇到了同樣的問題，把自 Auto Translate 關閉后、記得要點 save 保存一下才會生效哦。

**Comment by yetone** [comment]
这个问题在昨天发布的版本中已经完美修复！感谢反馈！
