### ISSUE TITLE
能否像chatgpt for google 一样支持输出结果的美化，自动换行

### ISSUE THREAD

**Issue by wcc526** [yetone/openai-translator#12]
https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

**Comment by yetone** [comment]
你好，一直是自动换行的，如果我理解有误的话可以给出一些例子截图吗？

**Comment by wcc526** [comment]
能支持显示markdown或代码片段那种原始html样式吗？

`
    targetTxt = targetTxt.replace(/\n/g, "<br>");

                                        <div className={styles.popupCardTranslatedContentContainer}>
                                            <div dangerouslySetInnerHTML={{ __html:translatedText }}></div>
                                            {/* {translatedText} */}
                                        </div>
`

我现在是这样处理的，做了一些改动，以便支持一些其他的prompt

**Comment by Jerry198384** [comment]
![无标题](https://user-images.githubusercontent.com/59760652/223085885-1feb9d90-26fc-41a6-b8cf-1278e995d00e.png)
應該是向劃詞翻譯這樣吧

**Comment by wcc526** [comment]
是的，这种展示效果会更好

**Comment by yetone** [comment]
@wcc526 @Jerry198384 十分感谢！我现在明白了，这就加上！

**Comment by yetone** [comment]
@wcc526 @Jerry198384 

现在已支持显示多行，安装最新版本即可

<img width="691" alt="Screenshot 2023-03-06 at 20 51 47" src="https://user-images.githubusercontent.com/1206493/223115496-5c6da561-308b-4cbf-bda9-d0dfa6fbb1b9.png">
