### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by hzcheney** [yetone/openai-translator#130]
Any plan that will support PDF selection and translation?

**Comment by szh-bash** [comment]
Use [pdf.js](https://mozilla.github.io/pdf.js) for now, check [demo](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by hzcheney** [comment]
> Use [pdf.js](https://mozilla.github.io/pdf.js) for now, check [demo](https://mozilla.github.io/pdf.js/web/viewer.html)

Awesome! Thank you for this amazing project!
