### ISSUE TITLE
openapi页面打不开耶，拿不到apikeys

### ISSUE THREAD

**Issue by mrr45** [yetone/openai-translator#14]
刷新了好几次都打不开，大家咋打开的？

**Comment by a1waysbeta** [comment]
我也是一样，但我注册了的，也能登陆上去

**Comment by a1waysbeta** [comment]
换个思路，打开首页 https://platform.openai.com/ 登录，然后点右上角个人头像，再点 View API Key 就可以了

**Comment by yetone** [comment]
这种属于网络的问题，先关闭了，还请谅解
