### ISSUE TITLE
网络代理功能

### ISSUE THREAD

**Issue by cencuansen** [yetone/openai-translator#142]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

能否加入网络代理配置。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JimSunJing** [comment]
赞同，下载的桌面端无法连接到 openai

**Comment by shaonianche** [comment]
#121

**Comment by JDYG** [comment]
不清楚现在的0.0.15版本是否使用了特殊的网络代理，以使得在大陆的用户更好地访问。我现在在国外尝试了windows的0.0.15版本，没有任何反应，既没有输出也没有报错。

**Comment by sunfch** [comment]
赞同

**Comment by Long-Ni** [comment]
赞同赞同赞同赞同

**Comment by woodypeckerwho** [comment]
> 不清楚现在的0.0.15版本是否使用了特殊的网络代理，以使得在大陆的用户更好地访问。我现在在国外尝试了windows的0.0.15版本，没有任何反应，既没有输出也没有报错。

旅美朋友反馈0.15 mac 版使用正常。

**Comment by Loongphy** [comment]
> 不清楚现在的0.0.15版本是否使用了特殊的网络代理，以使得在大陆的用户更好地访问。我现在在国外尝试了windows的0.0.15版本，没有任何反应，既没有输出也没有报错。

Same issue, no output on Windows version.

**Comment by yetone** [comment]
已经支持，感谢反馈！

**Comment by wangpre** [comment]
代理地址：https://api.openai-proxy.com
