### ISSUE TITLE
增加对windows端划词复制、应用置顶、代理配置的功能

### ISSUE THREAD

**Issue by royalrexwang** [yetone/openai-translator#144]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

感谢您创造这个工具，它大大提高了我工作的效率。因为我是windows用户，和其他客户端使用习惯有一定的差异。所以我提出两点关于功能改进的建议。
1. 增加划词复制。由于我大多数工作需要阅读pdf文档，在使用其他软件发现具有划词即选中粘贴到应用的功能。我希望用这种方式能提高输入信息的效率。
2. 增加窗口置顶。在持续性使用openai-translator中，我希望提高openai-translator的优先级，为了更快看到输出的结果，我希望它能被置顶。
3. 增加代理。在之前使用[lencx/ChatGPT](https://github.com/lencx/ChatGPT)时候我发现，通过挂一次美区代理能将代理保存到本地，下次使用能自动代理到美区，不需要打开代理软件也能实现跨服使用ChatGPT

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
已经支持，感谢反馈！
