### ISSUE TITLE
希望增加快捷键功能

### ISSUE THREAD

**Issue by ParanoidSu** [yetone/openai-translator#163]
### Search before asking

- [x] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

选中文本后按下设置的快捷键后客户端自动弹出并立马开始翻译选中的文本,类似deepL的功能。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
新版已经支持，感谢反馈！

**Comment by ParanoidSu** [comment]
试了下好像快捷键不支持同一个按键双击,比如ctrl+c+c是不支持的，希望大佬后续有空能优化一下。

**Comment by hcsu** [comment]
> 试了下好像快捷键不支持同一个按键双击,比如ctrl+c+c是不支持的，希望大佬后续有空能优化一下。

同样需要这个功能，希望可以支持「双击 alt」这种快捷键（来自 Bob 的习惯）
