### ISSUE TITLE
[Bug] UI 窗口无法纵向拖动

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#171]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.16

### System version

win11 22h2 pro

### Browser version

Chrome 111

### Minimal reproduce step

如图，在页面底端靠近任务栏的地方使用划词翻译
![image](https://user-images.githubusercontent.com/27895812/224269481-6f2ce228-0cb4-4f55-9847-65ccedd954a2.png)
此时生成的 UI 窗口无法纵向拖动，即使滚动浏览器页面完整显示出 UI 窗口后仍无法纵向拖动
![image](https://user-images.githubusercontent.com/27895812/224269632-bc1c79fe-fc28-45af-81d3-44db052277ab.png)

### What did you expect to see?

可以随意拖动 UI 窗口

### What did you see instead?

只可以水平（左右）拖动 UI 窗口

### Anything else?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by szh-bash** [comment]
只要初始生成的 UI 界面超出屏幕底部便无法纵向拖动

**Comment by yetone** [comment]
@imyuanx 能辛苦帮忙看一下这个 bug 吗？我刚刚验证了一下在这个 commit 之前的版本是好的：https://github.com/yetone/openai-translator/pull/95

**Comment by imyuanx** [comment]
由于之前是根据document高度定位的所以导致这个 Bug，我在 #162 里修复了这个问题

**Comment by imyuanx** [comment]
我验证了下似乎还是有这个问题，我来解决下

**Comment by yetone** [comment]
@imyuanx 辛苦了！感谢！
