### ISSUE TITLE
[Bug] 拖动 UI 窗口后始终跟随鼠标无法释放

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#181]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.16

### System version

win11-22h2-pro

### Browser version

chrome 111

### Minimal reproduce step

- 鼠标左键抓取 UI 窗口随意转几圈然后松开左键，有一定概率（50%）触发。
- 有时简单拖动一下松开左键也无法释放。

### What did you expect to see?

UI 窗口在最后的位置停住

### What did you see instead?

UI 窗口继续跟随鼠标，此时左键已松开

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by imyuanx** [comment]
我可以通过以下方式百分百触发：
快速拖动，当鼠标指针偏离标题栏时后再松开鼠标无法释放

**Comment by yetone** [comment]
这个问题已经在最新版本 `v0.0.17` 中修复

**Comment by szh-bash** [comment]
> 这个问题已经在最新版本 `v0.0.17` 中修复

敲碗等更新鸭！感觉修了这个看论文能 speed up 100%!

**Comment by yetone** [comment]
这个问题已经在 `v0.0.17` 中修复，且已经 release 了，大家去更新吧！

**Comment by szh-bash** [comment]
已解决
