### ISSUE TITLE
建议 截图并提取文本到程序内 像Microsoft PowerToys的Text Extractor

### ISSUE THREAD

**Issue by FmoX** [yetone/openai-translator#188]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

用于不支持选取文本的场景

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by szh-bash** [comment]
OCR ？想了解下现在有哪些低成本（实现、金钱）的方案，有开源的吗

**Comment by zaraiah** [comment]
这个pull request特别赞，能够本地上传图片进行识别。
https://github.com/yetone/openai-translator/pull/192
建议基于这个pull request将粘贴板中的截图快速的识别。

**Comment by zaraiah** [comment]
> 

我看https://github.com/yetone/openai-translator/pull/192用的是这个 https://github.com/naptha/tesseract.js

**Comment by zaraiah** [comment]
> OCR ？想了解下现在有哪些低成本（实现、金钱）的方案，有开源的吗

我看https://github.com/yetone/openai-translator/pull/192 用的是这个 https://github.com/naptha/tesseract.js
