### ISSUE TITLE
[Bug] Cannot set Hotkey

### ISSUE THREAD

**Issue by Yefee** [yetone/openai-translator#191]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.16

### System version

n/a

### Browser version

n/a

### Minimal reproduce step

Cannot set up hotkey in settings

### What did you expect to see?

n/a

### What did you see instead?

n/a

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yippp** [comment]
Cannot set hotkey on Windows too

**Comment by imyuanx** [comment]
Are you using chrome?
Please refresh your pages after changed hotkey.

**Comment by yetone** [comment]
The desktop application now supports setting keyboard shortcuts!

**Comment by KieSun** [comment]
@yetone why hotkey filter `meta`?

**Comment by wangxin1999** [comment]
无法设置command的快捷键

**Comment by Yefee** [comment]
> Are you using chrome? Please refresh the page after changing the hotkey.

I am on macOS 12.5.1

**Comment by yetone** [comment]
新版本已支持热键，感谢反馈！

**Comment by yetone** [comment]
> @yetone why hotkey filter `meta`?

tauri's shortcut library does not support meta.

**Comment by imyuanx** [comment]
> 

Maybe we can support meta for browser

**Comment by hfcui1** [comment]
好像不支持command热键

**Comment by AutumnStack** [comment]
怎么不支持command？deepl的都支持
