### ISSUE TITLE
希望作者给桌面端App增加一个置顶功能

### ISSUE THREAD

**Issue by ForestL18** [yetone/openai-translator#194]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

希望作者给桌面端App增加一个置顶功能，让App一直悬浮在所有窗口最顶层，方便阅读时实时划词翻译

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈！最新版已经支持置顶功能，请下载使用

**Comment by ForestL18** [comment]
> 感谢反馈！最新版已经支持置顶功能，请下载使用

最新Windows版本还是没有置顶按键
