### ISSUE TITLE
有没有更新「交互式翻译」的可能？

### ISSUE THREAD

**Issue by brick-pid** [yetone/openai-translator#2]
试用了贵插件，感觉很好用！
在使用过程中想到一个使用场景的拓展。

现有的场景是：
选择文本 => 翻译 => 结束

一个可能的翻译流程优化：
选择文本 => 翻译 => (提供继续与chatGPT对话的文本框) => 进一步追问文本中的某些概念、关键词 => 结束

![image](https://user-images.githubusercontent.com/51922962/222940959-adbc941c-ef3d-4a9c-9a2f-7a59130905e9.png)

**Comment by yetone** [comment]
现在已支持实时编辑翻译文本，交互式翻译是个很棒的想法！感谢你的建议！

![](https://user-images.githubusercontent.com/1206493/222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif)

**Comment by brick-pid** [comment]
> 现在已支持实时编辑翻译文本，交互式翻译是个很棒的想法！感谢你的建议！
> 
> ![](https://user-images.githubusercontent.com/1206493/222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif) [ ![222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif](https://user-images.githubusercontent.com/1206493/222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif) ](https://user-images.githubusercontent.com/1206493/222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif) [ ](https://user-images.githubusercontent.com/1206493/222957710-0a26a208-3bb2-441b-a489-bb6c74190a9f.gif)

太感谢啦！很激动能用上这么棒的插件😁！
