### ISSUE TITLE
[Bug] 还是会有不能移动的问题

### ISSUE THREAD

**Issue by devyujie** [yetone/openai-translator#202]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.17

### System version

Win10 LTSC 1809

### Browser version

Chrome 110.0.5481.180

### Minimal reproduce step

https://user-images.githubusercontent.com/48620527/224475498-3eb43e68-3271-4e83-8349-1320ffd5f497.mp4

### What did you expect to see?

显示翻译文本的区域，当行数超出设定的时候，加一个文本域

### What did you see instead?

翻译行数过多的时候，还会有不能纵向移动的问题

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by szh-bash** [comment]
边界情况没有穷尽啊 XD

**Comment by devyujie** [comment]
我更新了描述，能不能在下边也加一个这样的文本域
![image](https://user-images.githubusercontent.com/48620527/224475816-834d7006-0e39-44ad-866c-39c139f6c1f6.png)

**Comment by imyuanx** [comment]
本意是想把它固定在可视窗口之内
但是当它高度超过可视窗口的时候就出现了这个问题

**Comment by imyuanx** [comment]
如果在翻译后内容的区域增加滚动条的话也许体验会差一些

**Comment by szh-bash** [comment]
> 本意是想把它固定在可视窗口之内 但是当它高度超过可视窗口的时候就出现了这个问题

而且超过浏览器顶端后将无法再移动它，直接部分不可视了

![image](https://user-images.githubusercontent.com/27895812/224475921-40cb1e1f-3ddc-4e86-8f7a-4eb6ca0cdf23.png)

**Comment by imyuanx** [comment]
我能想到这三种方案，大家有什么想法吗？

![Snipaste_2023-03-11_17-27-27](https://user-images.githubusercontent.com/50652358/224476503-4668beb2-e123-49b6-a364-4a9de05976d7.png)

**Comment by szh-bash** [comment]
> 我能想到这三种方案，大家有什么想法吗？
> 
> ![Snipaste_2023-03-11_17-27-27](https://user-images.githubusercontent.com/50652358/224476503-4668beb2-e123-49b6-a364-4a9de05976d7.png)

第二种，然后可以让 Popup 顶部增长不越过浏览器上边界**或者**在越过之后可以拖下来吗？参考 [web](https://mozilla.github.io/pdf.js/web/viewer.html) 多行划词 Popup 顶部越过浏览器上边界死那儿了

**Comment by imyuanx** [comment]
实现了方案 2，双滚动条的实际体验很差
最终决定结合方案 2、3：基于 Document 定位，最大高度等于 Window
![Snipaste_2023-03-12_16-47-37](https://user-images.githubusercontent.com/50652358/224534644-faedb8c8-77b8-4a79-a29c-12c5b0925bb7.png)

**Comment by szh-bash** [comment]
> 实现了方案 2，双滚动条的实际体验很差 最终决定结合方案 2、3：基于 Document 定位，最大高度等于 Window ![Snipaste_2023-03-12_16-47-37](https://user-images.githubusercontent.com/50652358/224534644-faedb8c8-77b8-4a79-a29c-12c5b0925bb7.png)

之前的 bad case 似乎还是存在，我开了新 issue #235

**Comment by imyuanx** [comment]
这个问题在 PR #228 中修复，等待合并后的下一个新版本这个问题就解决了
