### ISSUE TITLE
[Bug] macOS出现界面重叠

### ISSUE THREAD

**Issue by L1cardo** [yetone/openai-translator#226]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.17

### System version

macOS 13.2.1

### Browser version

non

### Minimal reproduce step

打开自动翻译时，在app界面尝试修改翻译框内的内容时出现重叠
<img width="636" alt="image" src="https://user-images.githubusercontent.com/33802186/224534408-37773c77-19ce-4426-a78e-aa2369eb3432.png">

### What did you expect to see?

-

### What did you see instead?

-

### Anything else?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeffery9** [comment]
这个 应该是“画词” 功能造成的异常。

**Comment by yetone** [comment]
感谢反馈！这个已经在最新版中修复
