### ISSUE TITLE
[Bug] 点击复制内容按钮报错

### ISSUE THREAD

**Issue by Fred-Chan** [yetone/openai-translator#230]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.18

### System version

MacOS 13.2.1 

### Browser version

Chrome 110.0.5481.177

### Minimal reproduce step

鼠标移动到复制按钮，出现报错
`Something went wrong:

this.props.anchorRef.getBoundingClientRect is not a function. (In 'this.props.anchorRef.getBoundingClientRect()', 'this.props.anchorRef.getBoundingClientRect' is undefined)`

### What did you expect to see?

复制翻译内容

### What did you see instead?

报错信息
`Something went wrong:

this.props.anchorRef.getBoundingClientRect is not a function. (In 'this.props.anchorRef.getBoundingClientRect()', 'this.props.anchorRef.getBoundingClientRect' is undefined)`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
这个问题已经修复，刚刚发布了一个 hotfix 版本 v0.0.19，更新一下就好了
