### ISSUE TITLE
添加卸载时自动删除配置

### ISSUE THREAD

**Issue by aliuq** [yetone/openai-translator#231]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

卸载重装后，原先的配置还存在，不知道在哪个目录，希望能够手动清除

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yizhi996** [comment]
macOS 请删除 `~/Library/Application Support/xyz.yetone.apps.openai-translator/config.json`
windows 应该在 %APPDATA% 目录中

**Comment by yizhi996** [comment]
> > macOS 请删除 `~/Library/Application Support/xyz.yetone.apps.openai-translator/config.json` windows 应该在 `%APPDATA%` 目录中
> 
> Windows 下我没找到😭

在资源管理器输入 `%APPDATA%\xyz.yetone.apps.openai-translator`

**Comment by aliuq** [comment]
> > > macOS 请删除 `~/Library/Application Support/xyz.yetone.apps.openai-translator/config.json` windows 应该在 `%APPDATA%` 目录中
> > 
> > 
> > Windows 下我没找到😭
> 
> 在资源管理器输入 `%APPDATA%\xyz.yetone.apps.openai-translator`

不存在

![image](https://user-images.githubusercontent.com/11707934/224562784-5fd80ca1-0a7b-461c-95b9-b54cdf501fd9.png)

**Comment by yizhi996** [comment]
> 
真实路径`C:\Users\用户名\AppData\Roaming\xyz.yetone.apps.openai-translator`
还有`%APPDATA%` 的%不能少

**Comment by aliuq** [comment]
> > 
> 
> 真实路径`C:\Users\用户名\AppData\Roaming\xyz.yetone.apps.openai-translator` 还有`%APPDATA%` 的%不能少

看到了🤗
