### ISSUE TITLE
[Bug] Desktop App Requests Accessibility Permission Every Time it is Launched

### ISSUE THREAD

**Issue by MiracleXYZ** [yetone/openai-translator#233]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.19 (20230312.105555)

### System version

Ventura 13.2.1

### Browser version

n/a

### Minimal reproduce step

1. Open the app and grant accessibility permission when prompted.
2. Restart the app.

### What did you expect to see?

We expect to see nothing, as permission has already been granted.

### What did you see instead?

The app is requesting permission again, even though it has already been granted.

<img width="573" alt="Screenshot 2023-03-12 at 20 46 30" src="https://user-images.githubusercontent.com/30370926/224545628-f18e4c21-0848-4a91-9c1c-bad3be833bfb.png">

### Anything else?

I followed the instructions in README.md to remove and re-add the app in the settings list, but it did not work.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ernestyao** [comment]
Same problem.

**Comment by ernestyao** [comment]
I delete and add the option back in system setting. The prompt still persists.

**Comment by yetone** [comment]
If you have an M1/M2 chip, you can download the `aarch64` version of the dmg for installation. After installation, reset permissions according to the screenshot.

<img width="319" alt="Screenshot 2023-03-13 at 17 22 42" src="https://user-images.githubusercontent.com/1206493/224659493-4d50fca0-52f6-4693-aa79-d5eea6029d46.png">

![](https://user-images.githubusercontent.com/1206493/224536277-4200f58e-8dc0-4c01-a27a-a30d7d8dc69e.gif)

**Comment by ernestyao** [comment]
Solved with `aarch64` version.
