### ISSUE TITLE
[Bug] 浏览器划词右键翻译出现多余窗口

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#236]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.19

### System version

win11-22h2-pro

### Browser version

Chrome 111

### Minimal reproduce step

https://user-images.githubusercontent.com/27895812/224560159-2c974c1d-6901-490b-9dbe-de948680bc61.mp4

### What did you expect to see?

单个翻译窗口

### What did you see instead?

多了一个空白翻译窗口，而且限制在视频区域内无法拖离

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jianxiutou5** [comment]
+1，而且关不掉两个窗口

**Comment by szh-bash** [comment]
> +1，而且关不掉两个窗口

实测 v0.36 已经修复了，不知道在哪个版本修的。
