### ISSUE TITLE
显示音标

### ISSUE THREAD

**Issue by victorzone** [yetone/openai-translator#237]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

翻译英文单词时显示音标

### Solution

可不可以在划词翻译单词时，设计好prompt，让他显示音标。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
单词模式（只翻译单词）已经音标

**Comment by jinmiaoluo** [comment]
最近在阅读文档时，会遇到这样一个问题，在一个句子内，我知道单词的意思，但是我不知道自己的发音是否标准、然后就会想知道单词的音标。

现在的问题是，划词翻译并不会显示音标且选中单词复制黏贴（尝试作为一个单独的单词来查询），程序并不能很好的自动从划词翻译的状态自动切换为查询单词的状态，导致查询单词的音标存在困难。

**Comment by jinmiaoluo** [comment]
https://github.com/openai-translator/openai-translator/assets/39730824/0bd7808e-19a8-40dc-a8c3-38699431969e
