### ISSUE TITLE
明明已经填写了 API，但是却提示没有提供 API

### ISSUE THREAD

**Issue by xylagbx** [yetone/openai-translator#24]
已在 Extension options 里填写了 API，但是抓包看了一下，请求头、请求体里面都没有 API。

**Comment by Kern82** [comment]
![image](https://user-images.githubusercontent.com/127163250/223295575-b310590f-166d-4563-a6d1-e095ba8c1e72.png)
在网页的界面中，点开填写。

**Comment by xylagbx** [comment]
> ![image](https://user-images.githubusercontent.com/127163250/223295575-b310590f-166d-4563-a6d1-e095ba8c1e72.png) 在网页的界面中，点开填写。

网页界面里也试过了，都没用，点开显示已有 API，但翻译时就是反馈没有 API。

**Comment by Kern82** [comment]
是这个界面填的么

**Comment by xylagbx** [comment]
> 是这个界面填的么

<img width="441" alt="截屏2023-03-07 09 39 37" src="https://user-images.githubusercontent.com/50540847/223297066-71a50a34-3550-4668-b0db-fb811600f28a.png">
对啊，点开以后填写的

**Comment by xylagbx** [comment]
搞清楚了，AdGuard 的隐身模式搞得 🥲

-----------

隐身模式：
实际 IP 地址已隐藏
引用已隐藏
User-Agent 头部已隐藏
已移除第三方头部请求的身份验证
