### ISSUE TITLE
不能使用本地代理

### ISSUE THREAD

**Issue by xuefliang** [yetone/openai-translator#247]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

openai对地区限制太严格，有个本地代理地址类似这样http://localhost:8085/openai/v1，希望能openai-translate能支持一下，目前看着像跨域问题（CORS）引起的。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈，可以设置 API URL 的
