### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by skychx** [yetone/openai-translator#250]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.20 (20230312.164105)

### System version

macOS 12.6 (21G115) 
Apple M1 Pro

### Browser version

*

### Minimal reproduce step

Every time the APP is restarted, even if the accessibility permission has already been granted, the accessibility pop-up window will still appear.

### What did you expect to see?

The expected behavior is that the pop-up window should only appear once during the first time and not repeatedly in subsequent times.

### What did you see instead?

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/24872439/224638411-a639dc81-b659-4c96-bf8c-222e1a3a19c1.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ernestyao** [comment]
same as [#233 ]

**Comment by yetone** [comment]
If you have an M1/M2 chip, you can download the `aarch64` version of the dmg for installation. After installation, reset permissions according to the screenshot.

<img width="319" alt="Screenshot 2023-03-13 at 17 22 42" src="https://user-images.githubusercontent.com/1206493/224659493-4d50fca0-52f6-4693-aa79-d5eea6029d46.png">

![](https://user-images.githubusercontent.com/1206493/224536277-4200f58e-8dc0-4c01-a27a-a30d7d8dc69e.gif)

**Comment by ernestyao** [comment]
Yes. I confirm that it's solved in M1 Pro Macbook. But when you install, you should do as [#102] said.

**Comment by skychx** [comment]
> Yes. I confirm that it's solved in M1 Pro Macbook. But when you install, you should do as [#102] said.

I have uninstalled and reinstalled 3 times, but the problem still exists with `aarch64` on my M1 Pro.

**Comment by yetone** [comment]
@skychx Are you following the steps in the screenshot to delete and then re-add 'OpenAI Translator' in the 'Privacy & Security' interface?

**Comment by slipbox** [comment]
> > Yes. I confirm that it's solved in M1 Pro Macbook. But when you install, you should do as [#102] said.
> 
> I have uninstalled and reinstalled 3 times, but the problem still exists with `aarch64` on my M1 Pro.

I have the same problem.

**Comment by slipbox** [comment]
This problem was solved through https://github.com/yetone/openai-translator/issues/102#issuecomment-1461326485
