### ISSUE TITLE
浏览器插件能不能支持一个分屏模式，左边是原文，右边是翻译后的？这样阅读长文的效率可以提高很多

### ISSUE THREAD

**Issue by joostshao** [yetone/openai-translator#255]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

现在的翻译框会阻挡原文内容

### Alternatives

或者允许跳出一个独立的tab页面也能接受

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GrayXu** [comment]
这不是划词翻译的范围吧，建议看看[immersive-translate/immersive-translate](https://github.com/immersive-translate/immersive-translate)

**Comment by joostshao** [comment]
> 这不是划词翻译的范围吧，建议看看[immersive-translate/immersive-translate](https://github.com/immersive-translate/immersive-translate)

1： 不支持翻译本地通过浏览器打开的text文件，所以不适合，需要进一步适配文本文档。
2： 不喜欢中英文交叉的翻译模式，所以不适合个人体验习惯。
