### ISSUE TITLE
支持翻译chrome中打开的pdf

### ISSUE THREAD

**Issue by jtc1246** [yetone/openai-translator#256]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

支持翻译chrome中打开的pdf

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by 0x0918** [comment]
应该可以的，可以使用pdf.js https://github.com/mozilla/pdf.js
