### ISSUE TITLE
[Bug] 在VPN使用绕过中国大陆地址的情况下有时能用有时不行

### ISSUE THREAD

**Issue by jtc1246** [yetone/openai-translator#257]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.1.1

### System version

MacOS 12.3.1

### Browser version

Chrome 110.0.5481.177

### Minimal reproduce step

在我的设备上，源语言是英文，一定失败。源语言是中文，可能成功可能失败。

### What did you expect to see?

在VPN使用绕过中国大陆地址的情况下，可以正常运行

### What did you see instead?

在VPN使用绕过中国大陆地址的情况下，有时行有时不行。使用的是shadowrocket。在这种情况下，chatgpt和api都是可以正常使用的。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jtc1246** [comment]
<img width="531" alt="截屏2023-03-13 22 33 08" src="https://user-images.githubusercontent.com/43341500/224732676-70be0ad0-78b6-4142-b413-32271273ffbb.png">

**Comment by yetone** [comment]
这是网络环境和 OpenAI API 本身的问题，与此项目无关，所以先关闭了
