### ISSUE TITLE
最新Windows版本APP还是没有置顶按键

### ISSUE THREAD

**Issue by ForestL18** [yetone/openai-translator#270]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.20.0

### System version

Win10 22H2

### Browser version

无

### Minimal reproduce step

无

### What did you expect to see?

最新Windows版本APP出现置顶按键

### What did you see instead?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版的主界面已经有置顶按钮，之前的版本在托盘图标的右键菜单栏中
