### ISSUE TITLE
[Bug] windows 打开白屏

### ISSUE THREAD

**Issue by jiangying000** [yetone/openai-translator#283]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

https://github.com/yetone/openai-translator/releases/tag/v0.0.21

### System version

window 10

### Browser version

n/a

### Minimal reproduce step

install win x64 from https://github.com/yetone/openai-translator/releases/tag/v0.0.21
open it

### What did you expect to see?

run

### What did you see instead?

![image](https://user-images.githubusercontent.com/23182033/224986366-903a2a0d-eb78-469f-b618-a738b1940d57.png)A 
A white screen

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zsxplace** [comment]
我也是。

**Comment by whylist** [comment]
So did I.

**Comment by AgustinLin** [comment]
同
