### ISSUE TITLE
[Bug] 重复翻译问题

### ISSUE THREAD

**Issue by devyujie** [yetone/openai-translator#284]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.21

### System version

n/a

### Browser version

n/a

### Minimal reproduce step

n/a

### What did you expect to see?

选中一段文本，开始翻译；再选中一个单词，开始解释；这都没问题。

焦点再次聚焦到文本框的时候，会出现二次甚至多次重复翻译的情况。

https://user-images.githubusercontent.com/48620527/224982296-1711621f-6b9f-421c-99a6-9fe151d8c2fe.mp4

### What did you see instead?

希望文本只翻译一次。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈！已经在最新版修复！
