### ISSUE TITLE
希望加一个截图翻译的功能

### ISSUE THREAD

**Issue by Heresy-dd** [yetone/openai-translator#285]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

很多PDF文档或者需要付费下载的文档无法复制粘贴

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by demxiao** [comment]
+1，当然如果能使用Google的API来做OCR就再好不过。将成为windows下最好的翻译软件。

**Comment by sky390** [comment]
那我希望能使用 mathpix 的 api，这样公式也可以存在。

**Comment by Diaoxiaozhang** [comment]
+1

**Comment by yetone** [comment]
感谢建议，macOS 版已经支持截图 OCR
