### ISSUE TITLE
[Bug] 最大化按钮不起作用，具体表现为按下最大化按钮后实现最大化，再按无法缩小

### ISSUE THREAD

**Issue by HaloKala** [yetone/openai-translator#287]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.22

### System version

Windows11 H2

### Browser version

Chrome 111

### Minimal reproduce step

具体表现为按下最大化按钮后实现最大化，再按无法缩小

### What did you expect to see?

缩小窗口

### What did you see instead?

无法缩小窗口

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈！已经在最新版修复！

**Comment by HaloKala** [comment]
还有一个bug来不及在github提了，邮件说给你吧，Windows 11 22H2 下托盘图标鼠标悬停下只显示黑色气泡，没有显示名称。
另外，可否在单击托盘图标时候就可以直接复制到文本框里，目前需要先点击文本框聚焦。

yetone ***@***.***> 于 2023年3月14日周二 23:46写道：
