### ISSUE TITLE
Please support text-to-speech (TTS)

### ISSUE THREAD

**Issue by chaosky** [yetone/openai-translator#29]
ref: https://developer.chrome.com/docs/extensions/reference/tts/

**Comment by yetone** [comment]
This extension already supports TTS

**Comment by chaosky** [comment]
Sorry, my mistake, I didn't see the listen icon.  Can you please enhance it, perhaps through the use of Google Translate API? The default TTS on Linux does not sound very smooth.

ref: https://github.com/pndurette/gTTS/blob/main/gtts/tts.py

**Comment by yetone** [comment]
Great suggestion, I am looking for a TTS alternative.
