### ISSUE TITLE
点击图标显示翻译面板而不是设置面板

### ISSUE THREAD

**Issue by AnYiEE** [yetone/openai-translator#290]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

对于浏览器扩展来说，点击扩展图标显示翻译面板而不是设置面板我想应该是更合适的逻辑。

理由如下：
1. 某些页面因为安全原因不允许插入HTML。比如Chrome默认的新标签页，如果想翻译，在打开浏览器之后还要再随便打开一个第三方网页，再右键才能打开翻译面板。变动后可以无视当前页面的安全性要求，随用随开。
2. 步骤多。打开网页后，需要右键，还需要寻找并定位到对应的选项，而变动后只需要点一下图标。
3. 设置不会经常改动，翻译是主要功能。

设置面板可以放到翻译面板的角落，变成一个图标，作为二级面板。如果可以判断场景，也可以不要，浏览器扩展管理的页面里都有设置扩展的入口。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by maltoze** [comment]
有道理
