### ISSUE TITLE
[Close ISSUEs] The following issues should be closed as they are either finished, not related, or outdated.

### ISSUE THREAD

**Issue by okisdev** [yetone/openai-translator#292]
## Finished Issues
#4 #6 #13 #20 #30 #38 #44 #45 #121 #142 #144 #158 #163 #169 #180 #188 #190 #191 #221 #233 #250

## Not Related Issues
#14 #52 #53 #72

## Outdated Issues
#61 #78 #116 #155

**Comment by yetone** [comment]
Ha ha, thanks for the reminder!
