### ISSUE TITLE
Windows桌面版本如何修改API Code

### ISSUE THREAD

**Issue by Kern82** [yetone/openai-translator#296]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

RT

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
![](https://user-images.githubusercontent.com/20166026/225288593-afe38494-e044-4752-9b11-9494b25a6200.png)

**Comment by Kern82** [comment]
谢谢，找到了

**Comment by Heresy-dd** [comment]
我的为什么没有setting这个选项
