### ISSUE TITLE
有些網頁不能顯示翻譯按鈕.

### ISSUE THREAD

**Issue by Jerry198384** [yetone/openai-translator#3]
FC2作品里的介紹文字,不能顯示翻譯按鈕.

例如:
https://adult.contents.fc2.com/article/1660265/

**Comment by tsuilf** [comment]
Same with me. Did not work on any site.

**Comment by yetone** [comment]
@Jerry198384 你这个网站是因为在 iframe 中，我这周会解决这个问题，感谢反馈！

**Comment by yetone** [comment]
@tsuilf 可以检查一下是不是被其他的划词翻译图标覆盖了

**Comment by tsuilf** [comment]
> @tsuilf 可以检查一下是不是被其他的划词翻译图标覆盖了

汗，确实是这个问题，谢谢！

**Comment by yetone** [comment]
@Jerry198384 现在可以在你提供的这个网页进行翻译了，你更新一下最新版本试一下呢
