### ISSUE TITLE
add the right-to-left (RTL)

### ISSUE THREAD

**Issue by fontgah** [yetone/openai-translator#303]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

add the right-to-left (RTL) feature for Persian and Arabic translations to display

### 描述 Motivation

Hello, thank you for providing us with such an amazing extension and program for free. Please add the right-to-left (RTL) feature for Persian and Arabic translations to display the text correctly.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
Do you mean the incorrect position of the cursor in the translation result area when translating from an RTL page to an LTR language and vice versa, from an LTR page to an RTL language?

![image](https://user-images.githubusercontent.com/20166026/225259829-ba9766ef-7817-4804-b1d6-88f24d8dea72.png)
![image](https://user-images.githubusercontent.com/20166026/225260786-f19e493e-5d05-43bb-80f0-6aa8ad89ac45.png)

**Comment by fontgah** [comment]
Yes, by default, the Farsi translation content is on the left side, which is not readable
It should be fixed

https://chrome.google.com/webstore/detail/rtl-fixer/mkeclhaiiffmeeokkomoameekkpiiecf

https://imgur.com/a/58JxZSA

like this

سلام، ممنون از اینکه چنین افزونه و برنامه شگفت انگیزی را به صورت رایگان در اختیار ما قرار دادید. لطفاً ویژگی راست به چپ (RTL) را برای ترجمه فارسی و عربی اضافه کنید تا متن به درستی نمایش داده شود.

**Comment by OverflowCat** [comment]
@fontgah Hi, does the implementation of #317 look good to you?

**Comment by fontgah** [comment]
> @fontgah Hi, does the implementation of #317 look good to you? (screenshots attached in it)

Thank you very much for adding this feature. It has a bug, though. It doesn’t translate some texts and the system gives this message: “Translation could not interpret the text. Please provide a clear and translatable text.”

For example, please translate this text.

https://github.com/yetone/openai-translator/releases/tag/v0.0.25

fix: contextMenus error in firefox extension (#312)

feat: update userscripts

fix: trim selected word

fix: style pollution

feat: add clearHotkey (#316)

feat: update userscripts

fix: popupcard container overflow hidden

feat: update userscripts

fix: eslint

feat: support RTL text (resolves #303) (#317)

feat: add Azure OpenAI service support (#178)
![Untitled](https://user-images.githubusercontent.com/107890219/225552966-a634382c-5f77-4fef-a306-49dcfc69baf3.jpg)
