### ISSUE TITLE
更新之后翻译速度变慢  Translation speed slows down after updating

### ISSUE THREAD

**Issue by kitiho** [yetone/openai-translator#305]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

更新之后翻译速度变慢  Translation speed slows down after updating

### 描述 Motivation

更新之后翻译速度变慢  Translation speed slows down after updating

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
所有的更新中网络调用层没做任何改动，所有的更新都在 prompts 完善和 UI/UX 层面，所以可以先检查一下你的网络环境

https://github.com/yetone/openai-translator/blob/cbf45f086d681da205187bc174ff0d0a0f26031e/src/content_script/translate.ts#L154
