### ISSUE TITLE
[Bug] 阅读模式(reader view) 模式下，无法显示英语原文 

### ISSUE THREAD

**Issue by leyle** [yetone/openai-translator#307]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.1.2

### 系统/浏览器版本 System/Browser version

ubuntu 22.10 / vivaldi / 5.7.2921.63 (Stable channel) stable (64-bit) 

### 复现步骤 Reproduce step

1. 打开下面这个页面
[ethereumbook/01what-is.asciidoc at develop · ethereumbook/ethereumbook](https://github.com/ethereumbook/ethereumbook/blob/develop/01what-is.asciidoc)
2. 选择浏览器自带的阅读模式
3. 随意选择一段文字进行翻译
4. 无法显示原文（还有可能无法显示源语言版本）
5. 见下图所示

![2023-03-15_17-32](https://user-images.githubusercontent.com/1290013/225267775-8fe6af9e-6995-421f-872f-e6dc803e6862.png)

### 你看到了什么错误？What errors do you see?

无法显示翻译的原文

### 你期望看到什么？What did you expect to see?

正常显示原文

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版使用 shadow dom 来避免样式污染问题，请测试一下最新版

**Comment by leyle** [comment]
> 最新版使用 shadow dom 来避免样式污染问题，请测试一下最新版
 
好用，非常感谢
