### ISSUE TITLE
[Bug] 划词翻译弹出层，input样式被网页样式重置

### ISSUE THREAD

**Issue by olin2011** [yetone/openai-translator#315]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v1.4.0

### 系统/浏览器版本 System/Browser version

win11 chrome 版本 111.0.5563.64（正式版本）

### 复现步骤 Reproduce step

https://pypi.org/project/gpt-index/

### 你看到了什么错误？What errors do you see?

划词翻译弹出层，input样式被网页样式重置

### 你期望看到什么？What did you expect to see?

正常显示样式

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by olin2011** [comment]
版本是OpenAI Translator 0.0.21，看了别家版本了

**Comment by yetone** [comment]
最新版已经彻底解决这个问题，感谢反馈！
