### ISSUE TITLE
在翻译日文的时候，经常会误识别成中文

### ISSUE THREAD

**Issue by demxiao** [yetone/openai-translator#32]
大约有三分之一显然是日文的内容（日经新闻），会被误识别为中文，从而进行中英翻译（事实上是日英翻译）

**Comment by yetone** [comment]
可以给出用于复现问题的原始文本吗？

**Comment by demxiao** [comment]
厚生労働省が7日発表した1月の毎月勤労統計調査（速報、従業員5人以上の事業所）によると、1人当たりの賃金は物価変動を考慮した実質で前年同月比4.1%減った。10カ月連続の減少で、1月としては遡れる1991年以降で過去最大の減少幅だった。物価上昇が歴史的な水準に達し、賃金の伸びが追いつかない状況が続いている。

**Comment by catshitz** [comment]
语音也是会跳过平片假名只识别并读出汉字

**Comment by yetone** [comment]
@catshitz 语音问题是浏览器内置 TTS 的限制，正在考虑使用第三方 TTS 服务

**Comment by yetone** [comment]
@demxiao 你好，此问题已在最新版本中修复

<img width="767" alt="Screenshot 2023-03-07 at 19 54 49" src="https://user-images.githubusercontent.com/1206493/223415079-93d7a54b-4883-44a9-915a-03542e873c18.png">
