### ISSUE TITLE
[Bug] 打开插件后，patents.google.com 无法正常使用

### ISSUE THREAD

**Issue by AndersonGhost** [yetone/openai-translator#330]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.25

### 系统/浏览器版本 System/Browser version

Chrome 102.0.5005.167

### 复现步骤 Reproduce step

打开插件，patents.google.com 无法正常显示；

关闭插件，patents.google.com 正常显示使用；

### 你看到了什么错误？What errors do you see?

无

### 你期望看到什么？What did you expect to see?

打开插件应该可以正常打开patents.google.com

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by nickwzy** [comment]
v0.0.24也能复现

**Comment by yetone** [comment]
最新版已经彻底解决这个问题，感谢反馈！
