### ISSUE TITLE
[Bug] Firefox 扩展会导致某些页面错位 

### ISSUE THREAD

**Issue by j1g5awi** [yetone/openai-translator#345]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.1.4

### 系统/浏览器版本 System/Browser version

 Firefox 111.0

### 复现步骤 Reproduce step

进入我的自建 Miniflux 网站，不用登录即可发现页面往左错位：https://ttrss.maddestroyer.xyz/

### 你看到了什么错误？What errors do you see?

页面往左错位

### 你期望看到什么？What did you expect to see?

页面不变

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版已经彻底解决这个问题，感谢反馈！

**Comment by j1g5awi** [comment]
我已经更新到 0.1.5，仍有此问题。
