### ISSUE TITLE
请求缩小段间距

### ISSUE THREAD

**Issue by devyujie** [yetone/openai-translator#351]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

缩小段间距

### 描述 Motivation

![image](https://user-images.githubusercontent.com/48620527/225847152-02a36402-0171-4da8-b2df-aef106a0fb80.png)

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版已经解决此问题
