### ISSUE TITLE
[Bug] i18n还存在问题

### ISSUE THREAD

**Issue by wzdnzd** [yetone/openai-translator#354]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.1.5

### 系统/浏览器版本 System/Browser version

Chrome 111.0.5563.65

### 复现步骤 Reproduce step

1. 配置时，将语言设置为`简体中文`
2. 保存配置，点击插件图标，此时可以看到界面上的几个按钮是中文，如 `翻译`、`润色`等
3. 划词翻译，可以看到界面上的几个按钮还是英文的

### 你看到了什么错误？What errors do you see?

划词翻译时，界面上的几个按钮还是英文的

### 你期望看到什么？What did you expect to see?

界面上的几个按钮应该以中文显示

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by xavierskip** [comment]
我这里所有的i18n的选项都是失效的。版本 0.1.5 ，chrome 浏览器 110.0.5481.178。
