### ISSUE TITLE
[Bug] M2Pro Mac 无法打开应用，显示程序损坏

### ISSUE THREAD

**Issue by yq101101** [yetone/openai-translator#361]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.026/v0.027,两个版本都不行

### 系统/浏览器版本 System/Browser version

Ventura 13.0.0

### 复现步骤 Reproduce step

我这里直接打开就显示损坏

### 你看到了什么错误？What errors do you see?

<img width="273" alt="Screenshot 2023-03-17 at 22 27 49" src="https://user-images.githubusercontent.com/15857587/225934018-f9d9861b-2b88-42af-80ed-dc5e9a75048f.png">

### 你期望看到什么？What did you expect to see?

正常启动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ernestyao** [comment]
请阅读项目readme中MacOS Troubleshooting部分

**Comment by yq101101** [comment]
> 请阅读项目readme中MacOS Troubleshooting部分

Troubleshooting中有提及未认证开发者的问题，我遇到的问题并非是开发者认证的问题，而是直接提示应用被损坏

**Comment by ernestyao** [comment]
> > 请阅读项目readme中MacOS Troubleshooting部分
> 
> Troubleshooting中有提及未认证开发者的问题，我遇到的问题并非是开发者认证的问题，而是直接提示应用被损坏，并且以防万一，也照做了，可是并没有效果

`sudo xattr -d com.apple.quarantine /Applications/OpenAI\ Translator.app` 跑了吗？就这句解决损坏问题

**Comment by i5ean** [comment]
我也是13的系统 M2
一样是损坏，跟跑不跑上面那句没有关系
X64的提示 无法打开“OpenAI Translator”，因为无法验证开发者。
但是在系统 隐私和安全里面仍要打开就行了
aarch64的是什么都没有，就是损坏

**Comment by chongweiliu** [comment]
我m1pro的也是同样的问题

**Comment by ernestyao** [comment]
按作者之前的回复，我选了aarch64+跑上面的语句，是正常安装使用的，只是每次需要删除和添加一次辅助功能权限。
我的环境是macOS 13.2.1，M1 Pro 的 MBP，现在用0.0.27版。如果测试还不行的话，那只能等开发者回复了

**Comment by zhengle** [comment]
我运行那句后，问题解决。 (Pro 14, M1 Pro)

**Comment by yq101101** [comment]
尝试运行 sudo xattr -d com.apple.quarantine /Applications/OpenAI\ Translator.app 表示有效，当时在看TroubleShooting的时候，只看了权限问题，所以以为和崩溃无关，就没有执行这段。README中也许可以加上相关的操作避免相同的误会。
