### ISSUE TITLE
希望能接入GPT4 API

### ISSUE THREAD

**Issue by nickwzy** [yetone/openai-translator#366]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望能提供GPT4 API接口，已使用32K的TOKEN

### 描述 Motivation

如题

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by diemus** [comment]
这么快就通过gpt4的waitlist了吗

**Comment by nickwzy** [comment]
> 这么快就通过gpt4的waitlist了吗

是的，收到邮件可以用 8k的API。

**Comment by tao12345666333** [comment]
#387 has been merged. This one can be closed.
