### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yongqiangning** [yetone/openai-translator#372]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.27

### 系统/浏览器版本 System/Browser version

mac 

### 复现步骤 Reproduce step

英文翻译为中文后, 点击小喇叭, 没有声音发出来

### 你看到了什么错误？What errors do you see?

无

### 你期望看到什么？What did you expect to see?

希望有声音

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈！最新版已经支持 TTS
