### ISSUE TITLE
just copy pure text to clipboard

### ISSUE THREAD

**Issue by Chen1Plus** [yetone/openai-translator#384]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

just copy pure text to clipboard

### 描述 Motivation

hope the copy button will only copy pure text without any style

for example, if i polished some text from my document and tried to paste it back, i would need to use the "keep text only" button or it would be pasted with some style

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈，最新版已经支持此特性
