### ISSUE TITLE
[Bug] Aarch64版本文件损坏

### ISSUE THREAD

**Issue by shouyiwang** [yetone/openai-translator#386]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.30

### 系统/浏览器版本 System/Browser version

MacOS 13.2.1

### 复现步骤 Reproduce step

最近用的这些版本从来没成功过。每次一安装后打开就是文件损坏。必须下载x86的才行。

### 你看到了什么错误？What errors do you see?

文件损坏。

### 你期望看到什么？What did you expect to see?

正常运行。

### 还有其他的内容吗？Anything else?

bug一堆不知道干嘛也不改。。。
最重要的取词功能，热键按了以后窗口弹出，但是并没复制选取的内容。还得手动复制进去。
然后就是Mac的权限问题，每次升级后搞半天。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by BruceLEO1969** [comment]
Try this:
```
xattr -r -d com.apple.quarantine /Applications/OpenAI\ Translator.app/
```

**Comment by Dcsuzi** [comment]
> Try this:
> 
> ```
> xattr -r -d com.apple.quarantine /Applications/OpenAI\ Translator.app/
> ```

Thx, fixed it.

**Comment by Raychanan** [comment]
The solution above did not work for me. For those having the same issue, the following line might work for you.
```
xattr -cr "/Applications/OpenAI Translator.app"
```
