### ISSUE TITLE
提示error该怎么办？

### ISSUE THREAD

**Issue by zhang530809212** [yetone/openai-translator#39]
![image](https://user-images.githubusercontent.com/127180256/223338113-8d5fc387-fdbb-4ac6-81f7-e09a15dd0236.png)
提示error该怎么办？提示内容：You exceeded your current quota, please check your plan and billing details.

**Comment by yetone** [comment]
你的使用量已经超过了 OpenAI API 的免费额度，请购买 token 数：https://platform.openai.com/account/usage
