### ISSUE TITLE
Edge可以使用这个插件吗？

### ISSUE THREAD

**Issue by zhonghanwen** [yetone/openai-translator#4]

**Comment by yetone** [comment]
理论上是可以的，到时候我下载个 Edge 试一下

**Comment by qingweia** [comment]
可以

**Comment by zmfang** [comment]
mac下的edge没反应，chrome可以

**Comment by Kern82** [comment]
为了这个，特意从Edge改到Chrome。

**Comment by lee7de** [comment]
> 理论上是可以的，到时候我下载个 Edge 试一下

确实能行, pop up 和 options页面等都正常(0.0.11版)

**Comment by lee7de** [comment]
> > 理论上是可以的，到时候我下载个 Edge 试一下
> 
> 确实能行, pop up 和 options页面等都正常(0.0.11版)

![image](https://user-images.githubusercontent.com/48796862/223392375-905f5b01-545d-4f46-9464-00a84f3cdd3f.png)

**Comment by yetone** [comment]
感谢反馈，Edge 可以使用
