### ISSUE TITLE
[Bug] 取消一直显示图标后，无法打开

### ISSUE THREAD

**Issue by Ryan-the-hito** [yetone/openai-translator#406]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.31

### 系统/浏览器版本 System/Browser version

macos 12.6.3

### 复现步骤 Reproduce step

1-取消图标一直显示
2-重启软件发现没有用，于是卸载了
3-重新下载再安装，弹出窗口：无法打开软件。

### 你看到了什么错误？What errors do you see?

![fFDfm1U](https://i.imgur.com/fFDfm1U.png)

### 你期望看到什么？What did you expect to see?

能打开

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Ryan-the-hito** [comment]
我猜可能是软件需要运行一些 AppleScript 这样的命令，但是在 mac 上，有的命令是没有 icon 就无法运行的。我自己就遇到过。如果真实这样的话，或许可以把这个按钮去掉，一直有 dock icon 也不错的。

**Comment by Ryan-the-hito** [comment]
但现在的问题是，似乎软件会先 load user data，所以无法打开界面，而如果我需要更改这个 user data 就需要打开界面。需要解决这个 catch-22 的问题。（如果真是我上面说的这个问题的话）

**Comment by yetone** [comment]
好奇怪，「始终显示图标」是只针对浏览器插件的功能，是指划词的时候不显示图标，应该不会影响桌面端应用

**Comment by Ryan-the-hito** [comment]
啊？我下载的 mac 的版本也有，我还在想这好像是个新按钮，设置一下试试……
不过不知道这个是不是我打不开的原因……我在打不开之前只做了这件事😢

**Comment by Ryan-the-hito** [comment]
因为发现没有作用，就想着是不是自己设置得有问题，干脆重新下载一个看看
然后下载完了，去设置里面重新授予了权限（我想这个应该不会有问题吧）
回到 launchpad 点击启动，跳出弹窗。
之后试了介绍文档里面的命令，但发现也没有用，这个启动不起来好像不是同一个问题。

**Comment by yetone** [comment]
你是 M1/M2 芯片吗？

**Comment by Ryan-the-hito** [comment]
是的，我是 M1 mbp 2020。

**Comment by bluce-clj** [comment]
`sudo xattr -r -d com.apple.quarantine  /Applications/OpenAI\ Translator.app `

**Comment by Ryan-the-hito** [comment]
> 

Oh it worked!! Thanks!

**Comment by Ryan-the-hito** [comment]
虽然不知道问题的原因是什么，但似乎上面这个 command 能有效解决问题~
Although I don't know the reason for the problem, it seems that the above command can effectively solve the problem~

**Comment by yetone** [comment]
@Ryan-the-hito 看起来是 README 里提到的这个问题，谢谢反馈！

<img width="770" alt="Screenshot 2023-03-21 at 19 10 16" src="https://user-images.githubusercontent.com/1206493/226589192-70d06342-3fbc-4959-93c6-dfe3241a5913.png">

**Comment by Ryan-the-hito** [comment]
> @Ryan-the-hito 看起来是 README 里提到的这个问题，谢谢反馈！
> 
> <img alt="Screenshot 2023-03-21 at 19 10 16" width="770" src="https://user-images.githubusercontent.com/1206493/226589192-70d06342-3fbc-4959-93c6-dfe3241a5913.png">

很奇怪，我当时试了 README 里面的这个命令，但是没有用。
这位朋友给的命令多了一个 -r，我不太懂，不知道是不是多赋予了一个权限，我不抱希望地试了一下，但似乎解决了问题，可以用了。
所以我不清楚是不是同一个问题导致的。🤔
