### ISSUE TITLE
[Bug] Can not invoke by clicking the Dock on MacOS 在窗口关闭后无法在边栏唤起应用

### ISSUE THREAD

**Issue by 623059008** [yetone/openai-translator#421]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.28 (20230318.170252)

### 系统/浏览器版本 System/Browser version

macOS 12.6.3

### 复现步骤 Reproduce step

1. 打开应用
2. 点击关闭(应用处于后台存活状态)
3. 点击Dock处OpenAI Translator的图标，无反应

只要该应用进入后台，则必须手动结束OpenAI Translator应用进程，再次打开才可以，否则无法唤起Translator的主界面

### 你看到了什么错误？What errors do you see?

只要该应用进入后台，则必须手动结束OpenAI Translator应用进程，再次打开才可以，否则无法唤起Translator的主界面

### 你期望看到什么？What did you expect to see?

点击Dock,该应用主界面可以正常被唤起,因为此应用在后台显示依然存活.
不需要手动结束后台进程才可以重新唤起

### 还有其他的内容吗？Anything else?

No

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
可以试一下最新版 `v0.0.32`

**Comment by vinchibana** [comment]
> 可以试一下最新版 `v0.0.32`

已更新至 `v0.0.34` 依然有此问题

**Comment by Maxwell-Walker** [comment]
v0.0.36 也依然有此问题，希望尽快解决，太影响体验了

**Comment by yetone** [comment]
最新版已修复这个问题
