### ISSUE TITLE
[Bug] 0.0.32版本，windows10下运行时不能弹出对话框，一直在任务栏

### ISSUE THREAD

**Issue by zhuqingcode** [yetone/openai-translator#424]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.32

### 系统/浏览器版本 System/Browser version

windows10 企业版 LTSC

### 复现步骤 Reproduce step

1.双击打开；

### 你看到了什么错误？What errors do you see?

1.没有错误

### 你期望看到什么？What did you expect to see?

弹出对话框

### 还有其他的内容吗？Anything else?

没有

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by zhuqingcode** [comment]
已尝试，还是不行；安装后，啥都不修改，双击没有对话框弹出，只能工作在后台（隐藏的任务栏）；之后，我修改以兼容性（Windows7兼容模式）运行这个程序，可以出现在任务栏，但是仍然不能弹出对话框，谢谢！

**Comment by Co5mos** [comment]
> 已尝试，还是不行；安装后，啥都不修改，双击没有对话框弹出，只能工作在后台（隐藏的任务栏）；之后，我修改以兼容性（Windows7兼容模式）运行这个程序，可以出现在任务栏，但是仍然不能弹出对话框，谢谢！

+1

**Comment by volovteche** [comment]
退回到v0.0.26版本，终于能用了

**Comment by zhuqingcode** [comment]
> 

+1

**Comment by zhuqingcode** [comment]
> 退回到v0.0.26版本，终于能用了

+1

**Comment by 0xFin** [comment]
> 退回到v0.0.26版本，终于能用了

+1
但缺少了窗口固定功能。希望最新版本可以尽快修复无法显示窗口的问题

**Comment by NeoVV** [comment]
Mac电脑，同样是无法显示窗口问题

**Comment by zhuqingcode** [comment]
问下开发大佬，这个问题解决了吗？谢谢

**Comment by zhuqingcode** [comment]
亲测已解决
