### ISSUE TITLE
统一 Chrome Webstore 和 github release 版本号

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#426]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

如题

### 描述 Motivation

根本不知道web商城提供的究竟是哪个版本哈哈！

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
可以默认 Chrome Web Store 里的是最新版本

**Comment by devyujie** [comment]
确实难分辨，如果不方便统一版本号的话，在设置页面里加一个 `Github Version` 也行

**Comment by szh-bash** [comment]
> 可以默认 Chrome Web Store 里的是最新版本

每次更新 [Latest](https://github.com/yetone/openai-translator/releases/latest) 版本商场里也会立刻同步更新的意思？
