### ISSUE TITLE
is:issue is:open 新版本太难用了，简单翻译就好了啊，我不需要给我讲那么多英语知识，还浪费token。 可以做个开关呀

### ISSUE THREAD

**Issue by vegetax** [yetone/openai-translator#431]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

is:issue is:open 新版本太难用了，简单翻译就好了啊，我不需要我讲那么多英语知识，还浪费token

### 描述 Motivation

is:issue is:open 新版本太难用了，简单翻译就好了啊，我不需要我讲那么多英语知识，还浪费token

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ttyy33** [comment]
我觉得也是，例句我觉得可以写，但是那个音标写的，我都对不上。

**Comment by Dca3fu3** [comment]
是的，或者可以弄个设置，有需要的人自行开启。

**Comment by devyujie** [comment]
翻译段落时出现例句是个小bug，已修复 #433 ，音标的话，在不选中单个单词的情况下，是不会被触发的。不过确实可以给“开启单词例句模式”加个开关。

**Comment by yetone** [comment]
不好意思，最新版本已经修复英文句子也会显示音标和例句的问题
