### ISSUE TITLE
很好的插件，但用起来有点卡

### ISSUE THREAD

**Issue by Kayce001** [yetone/openai-translator#44]
有时候卡，然后就报错

**Comment by yetone** [comment]
感谢你的反馈！请问你的电脑是什么配置啊？卡的时候可以辛苦打开 Task Manager 截个图给我吗？

<img width="751" alt="Screenshot 2023-03-07 at 18 08 15" src="https://user-images.githubusercontent.com/1206493/223390829-045515be-4a01-4c5d-8e0c-2946980be99d.png">

**Comment by Kayce001** [comment]
现在好了，不过有时候拉翻译框释放不了（需要点到上部分），导致有时候用起来有点麻烦。如果设置成二次点击自动释放感觉会更好些。
![2023-03-09 11-16-22 的屏幕截图](https://user-images.githubusercontent.com/83959004/223907499-bbc6b965-291d-47e9-bb38-6baf6bd583db.png)
