### ISSUE TITLE
[Bug] The popup can not be called out on a website.

### ISSUE THREAD

**Issue by drafting-dreams** [yetone/openai-translator#450]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

browser extension 0.1.8

### 系统/浏览器版本 System/Browser version

macOS 13.2.1 Chrome 111.0.5563.64

### 复现步骤 Reproduce step

1. Goto https://learnxinyminutes.com/docs/python/ 
2. Select any texts in the page
3. Click the translator icon
4. Can not See the translator UI

### 你看到了什么错误？What errors do you see?

Can not call out the translator UI

### 你期望看到什么？What did you expect to see?

Can call out the translator UI, and see the translation result

### 还有其他的内容吗？Anything else?

NA

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by szh-bash** [comment]
![image](https://user-images.githubusercontent.com/27895812/227447683-170d8a2b-f578-4113-abeb-cdf859eeea6a.png)
Try v0.0.34?

**Comment by drafting-dreams** [comment]
I checked again and it's working now. (I'm still using the same version as 0.1.8)

It's weired it didn't work yesterday even if I close and reopen the page. It seemed something was loaded to the DOM because I could see the scroll bar position was changed but without seeing the popup.

But since it's recovered, maybe it's just a temporary phenomenon.
Thanks for checking.
