### ISSUE TITLE
[Bug] 特定网页 Popup 无法自由移动

### ISSUE THREAD

**Issue by szh-bash** [yetone/openai-translator#459]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.34

### 系统/浏览器版本 System/Browser version

Chrome 111

### 复现步骤 Reproduce step

网址：https://en.wikipedia.org/wiki/StyleGAN

https://user-images.githubusercontent.com/27895812/227279612-362fa348-f5b9-4e4e-a58f-61d513b58357.mp4

### 你看到了什么错误？What errors do you see?

Popup 无法上下移动，仅能左右移动

### 你期望看到什么？What did you expect to see?

Popup 自由移动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by itning** [comment]
请问这个
<img width="593" alt="image" src="https://user-images.githubusercontent.com/19759891/227426773-5f8e4ed7-665e-45cf-b694-8c6beeb36032.png">
图标能否支持移动，如果不支持能否帮忙修改位置，例如右移几px
现在和其它翻译工具重叠了 例如google翻译

**Comment by szh-bash** [comment]
> 请问这个 <img alt="image" width="593" src="https://user-images.githubusercontent.com/19759891/227426773-5f8e4ed7-665e-45cf-b694-8c6beeb36032.png"> 图标能否支持移动，如果不支持能否帮忙修改位置，例如右移几px 现在和其它翻译工具重叠了 例如google翻译

另外 new 一个 issue 吧

**Comment by itning** [comment]
> > 请问这个 <img alt="image" width="593" src="https://user-images.githubusercontent.com/19759891/227426773-5f8e4ed7-665e-45cf-b694-8c6beeb36032.png"> 图标能否支持移动，如果不支持能否帮忙修改位置，例如右移几px 现在和其它翻译工具重叠了 例如google翻译
> 
> 另外 new 一个 issue 吧

#480

**Comment by szh-bash** [comment]
> 已提交pr [Here](https://github.com/yetone/openai-translator/pull/471)

v0.36 已解决
