### ISSUE TITLE
[Bug] Ubuntu Wayland 桌面版白屏

### ISSUE THREAD

**Issue by houz42** [yetone/openai-translator#474]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.34 AppImage

### 系统/浏览器版本 System/Browser version

Ubuntu 22.04 LTS, 5.19.0-35-generic, wayland, sway desktop

### 复现步骤 Reproduce step

安装 v0.0.34 AppImage, 从系统托盘图标打开应用 (Show)

### 你看到了什么错误？What errors do you see?

白屏

### 你期望看到什么？What did you expect to see?

正常工作

### 还有其他的内容吗？Anything else?

- 系统托盘图标正常
- 白屏窗口右键菜单可以显示
  ![image](https://user-images.githubusercontent.com/4497443/227693415-a1c09fd9-2baa-4404-87fb-16658284dfa8.png)
- v0.0.27 窗口可以正常打开, 大部分功能正常
- v0.0.28 及以上都有这问题
- deb 版本同样

感谢各位作者的努力. 我并不着急修复, 只是提醒其他类似用户先使用旧版或者浏览器插件.

我明白使用 linux, wayland 桌面环境的是少数用户, 修复起来也很麻烦. 而且就算修复了这个问题, 还有很多其他问题, 例如之前观察到输入框不支持 IME (fcitx5 + rime).

我不太熟悉桌面开发, 哪位朋友有兴趣的话我可以配合 debug.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by houz42** [comment]
另外, 建议细分桌面版 bug 的环境, 方便用户和开发者查找, 例如按操作系统, CPU 架构等. 例如 mac 版本也曾经有过白屏问题, 已经修复, 但似乎和 linux 版本没有关系.

**Comment by Xuanwo** [comment]
Archlinux 上也有类似的问题

**Comment by tang-hi** [comment]
同样的问题,我通过在命令行中直接运行AppImage,看到以下的报错信息，希望可以有帮助
![image](https://user-images.githubusercontent.com/72755185/227766025-a05925a9-2884-4b25-8f9c-66f468159e18.png)
