### ISSUE TITLE
为什么使用时会说我超过免费配额了呢

### ISSUE THREAD

**Issue by Shimmerlei** [yetone/openai-translator#48]
当我划词翻译时，在翻译栏显示“error”，并说明：you exceeded your current quota, please check your plan and billing details.
请问这是什么问题？我该如何解决？

**Comment by woodypeckerwho** [comment]
貌似“同一手机号”注册的第一个openapi账号有18美元的免费token配额，注册的第二个及以后的账号无免费api token配额。

**Comment by Shimmerlei** [comment]
> [woodypeckerwho](/woodypeckerwho)
感谢！确实注册完它说我这个手机号已经注册过了，那我换回第一个账号试试

**Comment by KKBBQLIU520199** [comment]
我也同样遇到这种情况，我查看了当月Usagae，0额度..不是说新账号有$18 免费额度吗？我怀疑是不是我没添加支付方式的问题？

**Comment by zrdsj** [comment]
> 

There is no problem with your understanding. The API’s $18 quota itself has a time limit. Even if you only use it a little bit after it expires, you can’t continue to use it.

**Comment by XxSbyH** [comment]
> 

求后续，我也出现同样的问题，已使用是0
