### ISSUE TITLE
[Bug] Encountered not-supported-region warning message (#userscript, #Tampermonkey)

### ISSUE THREAD

**Issue by celerysoft** [yetone/openai-translator#482]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.35 Pre-release

### 系统/浏览器版本 System/Browser version

Chrome 111.0.5563.110

### 复现步骤 Reproduce step

1. select some text
2. click OpenAI Translator icon

### 你看到了什么错误？What errors do you see?

A warning info:

**We were unable to check if your IP address is in a [supported region](https://platform.openai.com/docs/supported-countries) of OpenAI. Please check your Internet connection, and ensure that you are accessing the API in a supported region of OpenAI, or your account may get banned regardless of your GPT Plus subscription status or any remaining account balance.**

So the translation work has not been completed.

### 你期望看到什么？What did you expect to see?

The translation result

### 还有其他的内容吗？Anything else?

I created an issue [443](https://github.com/yetone/openai-translator/issues/443) before, Today I see that the latest version v0.0.35 is released (although it is in pre-release status), so I update and try it out immediately. The issue from the 443 is resolved, but today I encounter this new problem.

I know that in v0.0.35 a request will be sent to [https://chat.openai.com/cdn-cgi/trace](https://chat.openai.com/cdn-cgi/trace) to check the user's location, but I'm certain that my location is in the US, the warning message(not supported region) still shows. I'm wondering if this could be an issue with the code running under Tampermonkey.

Here is my result of that request:
```
fl=452f230
h=chat.openai.com
ip=1.1.1.1(fake but the real one is an ip from the US)
ts=1679767262.9
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
colo=EWR
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
```

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by superman66** [comment]
I have encountered the same issue

**Comment by echo672** [comment]
Me too!   I am using this extension on Firefox 111.0.1 in Debian system, and encountered the same issue. But another extension did not have the issue.
