### ISSUE TITLE
Firefox 插件提示 unable to check if your IP address is in a supported region 

### ISSUE THREAD

**Issue by gemnioo** [yetone/openai-translator#485]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

Firefox Version 0.1.9;  macOS 0.0.34 

### 系统/浏览器版本 System/Browser version

macOS Venture  13.2.1   Firefox 0.0.34 

### 复现步骤 Reproduce step

使用相同的API Key  macOS 或者其他套壳iOS 客户端均能使用  而Firefox 插件提示 .... unable to check if your IP address is in a supported region  ...... 

### 你看到了什么错误？What errors do you see?

<img width="766" alt="截圖 2023-03-26 10 28 06" src="https://user-images.githubusercontent.com/20894536/227752933-c35ed8be-05fe-4176-8632-627d234e9fcd.png">

### 你期望看到什么？What did you expect to see?

看起来没有被Ban 账户  因为除了Firefox 插件之外均可使用； 
另外因为Open AI Ban 账户给开发者带来很大的误解  感谢yetone日更的无私付出 🎉 

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by nathan60107** [comment]
同樓主的問題
附加元件同為0.1.9
OS WIN10
![圖片](https://user-images.githubusercontent.com/18046878/227760264-b427319d-88ca-4c42-b118-4dc7d65002e5.png)
我看起來是來源語言壞了不會採用自動語言
如果我手動選了來源與目標語言後就會正常翻譯
![圖片](https://user-images.githubusercontent.com/18046878/227760284-dd5b4cac-55bc-4d99-9f79-79d8d2b0b0dd.png)
台灣的IP是不可能被openAI封的
其他使用api的附加元件也都正常運作
希望能早日修復(畢竟免費的額度好像只能用到4/1了 之後可能就沒得免費用了
同樣感謝yetone的付出

**Comment by gemnioo** [comment]
复现了@nathan60107 的情况 同时测试了 Chrome 安装最新版  目前似乎只有Firefox 遇到以上问题 手动选择 目标语言之后能使用  
<img width="1275" alt="截圖 2023-03-26 17 49 57" src="https://user-images.githubusercontent.com/20894536/227768718-35291a19-e91d-4adf-afb7-9cf4f2e7f5d8.png">
<img width="1328" alt="截圖 2023-03-26 18 02 20" src="https://user-images.githubusercontent.com/20894536/227768721-8afb3938-0f6b-4da2-838a-89c7f231305a.png">

**Comment by soeyu** [comment]
https://github.com/yetone/openai-translator/blob/c0545373a3764fbc6be6e17da8d44edcc78f1c25/src/common/geo.ts#L42
![图片](https://user-images.githubusercontent.com/3954659/227769617-a585b9fa-a63d-4bcb-8516-3f4f1b9f8dd2.png)

火狐在执行时会报错，请求中断了，重新绑定一下window就可以了 window.fetch.bind(window)

**Comment by soeyu** [comment]
https://github.com/yetone/openai-translator/blob/c0545373a3764fbc6be6e17da8d44edcc78f1c25/src/common/geo.ts#L42
![图片](https://user-images.githubusercontent.com/3954659/227770119-0c44b75a-3a80-47de-b48b-036fe7bd71c6.png)
火狐执行时报错了，改一下就可以了window.fetch.bind(window)

**Comment by nathan60107** [comment]
@soeyu 事情變得有點奇怪
0.1.10版雖然自動語言的問題修好了
但是ip的問題依舊
還是說這是不同的問題?
![圖片](https://user-images.githubusercontent.com/18046878/228526660-a1c087f6-38fc-45c6-8df9-2cf544321c72.png)

**Comment by soeyu** [comment]
> @soeyu 事情變得有點奇怪 0.1.10版雖然自動語言的問題修好了 但是ip的問題依舊 還是說這是不同的問題? ![圖片](https://user-images.githubusercontent.com/18046878/228526660-a1c087f6-38fc-45c6-8df9-2cf544321c72.png)

判断ip是使用前端请求，会有网站有csp跨域问题；翻译是在background进行，之前修好了，没这个问题。两个功能是独立的。

**Comment by nathan60107** [comment]
> 
> 判断ip是使用前端请求，会有网站有csp跨域问题；翻译是在background进行，之前修好了，没这个问题。两个功能是独立的。
那再麻煩大佬修復了，是說我還想額外提一個功能，就是能不能增加一個選項關掉逐字回答，讓他一口氣回答完，對於閱讀快的語言來說逐字實在是蠻慢的，還要等他慢慢出現，一口氣回答完個人認為UX會比較好，畢竟翻譯不需要仿說話一個字一個字說。

**Comment by gemnioo** [comment]
“畢竟翻譯不需要仿說話一個字一個字說"   大语言模型的 feature 就是统计模型一个个蹦字 

另外不是因为 机场UDP的问题导致的么？ OpenAI网页端 是网站启用了 http3 ，基于 quic ，基于 udp   https://www.v2ex.com/t/900491#r_12708197

调动API应该不会遇到这样的问题  [https://chat.openai.com/cdn-cgi/trace](https://t.co/wILTLTJbLp)  确实是美国地址

同样 macOS 和 Chrome 插件 都没有此问题  是 Firefox 的原因导致的
