### ISSUE TITLE
"Internal server error"

### ISSUE THREAD

**Issue by Jerry198384** [yetone/openai-translator#50]
chat.openai.com可以正常訪問,但插件翻譯會顯示"Internal server error".請問有什麼解決方法.謝謝!

**Comment by yetone** [comment]
OpenAI API 服务挂了，因为众所周知的微服务的优秀的故障隔离特性，网页端服务正常并不代表 API 服务正常

**Comment by Jerry198384** [comment]
好的 謝謝你的回答
