### ISSUE TITLE
你好，使用edge浏览器遇到了错误：You exceeded your current quota, please check your plan and billing details.怎么解决

### ISSUE THREAD

**Issue by Hitori-Nari** [yetone/openai-translator#52]

**Comment by woodypeckerwho** [comment]
参见：
https://github.com/yetone/openai-translator/issues/48#issuecomment-1458009224

**Comment by yetone** [comment]
> 参见： [#48 (comment)](https://github.com/yetone/openai-translator/issues/48#issuecomment-1458009224)

感谢提供
