### ISSUE TITLE
可以正常使用，但有报错信息出现。

### ISSUE THREAD

**Issue by zhu-hongwei** [yetone/openai-translator#521]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

OpenAI Translator0.1.10

### 系统/浏览器版本 System/Browser version

chrome 版本 111.0.5563.110（正式版本） (x86_64)

### 复现步骤 Reproduce step

<img width="588" alt="image" src="https://user-images.githubusercontent.com/61079864/228402664-4c83ca1d-0b2a-4a15-b902-7439157414f0.png">

---

<img width="294" alt="image" src="https://user-images.githubusercontent.com/61079864/228402680-64c39d71-a05f-4c58-af59-cd1e2555addb.png">

---

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61079864/228403135-310f553a-ae66-4f8d-ac22-85dfd874e97a.png">

### 你看到了什么错误？What errors do you see?

如上图

### 你期望看到什么？What did you expect to see?

没有报错

### 还有其他的内容吗？Anything else?

no
我愿意提交一份 PR 来修改这个错误，但是没那个实力。。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by AndersonGhost** [comment]
应该是代理IP有问题。不能使用机房公共IP，这样可能会导致OpenAI被封号的。

**Comment by OverflowCat** [comment]
请访问 https://chat.openai.com/cdn-cgi/trace 查看你当前 IP 信息

**Comment by zhu-hongwei** [comment]
fl=446f192
h=chat.openai.com
ip=67.21.64.114
ts=1680071809.648
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
colo=LAX
sliver=010-lax06
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519

**Comment by OverflowCat** [comment]
🤔那应该是 Ghelper 没有代理扩展的网络请求？我待会测试一下

**Comment by OverflowCat** [comment]
你先试试关掉智能模式［PAC］这个选项

**Comment by zhu-hongwei** [comment]
关掉智能模式［PAC]，貌似没有效果。

这个问题貌似不是必现的。

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/61079864/228449711-4750781f-96ba-4fdc-96bb-942b8aa57be7.png">

**Comment by SchneeHertz** [comment]
建议加上关闭这个提示框的设置
在不被支持的地区使用openai的服务虽然有风险，但如果用户确认过，没有必要每次都弹出这个提示
