### ISSUE TITLE
桌面端建议增加自动更新功能

### ISSUE THREAD

**Issue by Cyiming** [yetone/openai-translator#524]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

桌面端建议增加自动更新功能

### 描述 Motivation

现在软件更新比较频繁 能自动更新可以方便用户更新到最新版本

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
自动更新的功能已经增加～
