### ISSUE TITLE
prompt还是有一些问题？回复了其他信息

### ISSUE THREAD

**Issue by ljz2021** [yetone/openai-translator#54]
version: 0.0.12

情况是，8点钟api炸了的时候，一直在尝试重新使用api，api恢复的时候出现了以下错误。但是当时openai的status是报了model error的:
[Elevated error rates on all models.](https://status.openai.com/incidents/75n0s8jzv5gx)，不确定之后是否还会出现这个问题（目前：中国时间：3/7/21:47，同样的内容依然可以复现问题）

![photo_2023-03-07_20-14-04](https://user-images.githubusercontent.com/38675066/223440351-34621817-2acc-4277-a482-eee789624f2e.jpg)

**Comment by yetone** [comment]
感谢反馈，已经加入 base cases 嘉年华：https://github.com/yetone/openai-translator/discussions/58

**Comment by ljz2021** [comment]
> 感谢反馈，已经加入 base cases 嘉年华：#58

感谢大佬的付出，这个插件非常非常的好用，愿大佬天天好心情~（此条不用耽误时间回复了:D）
