### ISSUE TITLE
窗口能否保持在前？

### ISSUE THREAD

**Issue by pengchengau** [yetone/openai-translator#556]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.36

### 系统/浏览器版本 System/Browser version

Mac OS

### 复现步骤 Reproduce step

窗口能否保持在前？用来对照，这个功能很实用

### 你看到了什么错误？What errors do you see?

窗口能否保持在前？用来对照，这个功能很实用

### 你期望看到什么？What did you expect to see?

窗口能否保持在前？用来对照，这个功能很实用

### 还有其他的内容吗？Anything else?

窗口能否保持在前？用来对照，这个功能很实用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/1206493/229346800-530cdf37-e0f6-44a4-818d-1929c8ac1735.png">

你好，这个功能已经支持，选择 pin 即可

**Comment by pengchengau** [comment]
mac桌面版没有看到呢？
