### ISSUE TITLE
[Feat] Support Azure OpenAI

### ISSUE THREAD

**Issue by jhhuang96** [yetone/openai-translator#560]
### feature

Support Azure OpenAI

### Motivation

Azure OpenAI Service provides REST API access to OpenAI's powerful language models including the GPT-3, Codex and Embeddings model series. ([link](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview))

Azure OpenAI Service gives customers advanced language AI with OpenAI GPT-4, GPT-3, Codex, and DALL-E models with the security and enterprise promise of Azure. Azure OpenAI co-develops the APIs with OpenAI, ensuring compatibility and a smooth transition from one to the other.

With Azure OpenAI, customers get the security capabilities of Microsoft Azure while running the same models as OpenAI. Azure OpenAI offers private networking, regional availability, and responsible AI content filtering.

**Comment by ljz2021** [comment]
It is already supported now.

**Comment by jhhuang96** [comment]
Thanks, I found it.

https://github.com/yetone/openai-translator/pull/506
