### ISSUE TITLE
建议API地址可自定义(照顾墙内)，Chrome内划词后可快捷键直接唤起开始翻译，背景可自适应网页背景

### ISSUE THREAD

**Issue by jarlin8** [yetone/openai-translator#6]
- 建议API地址可自定义(照顾墙内) eg.  api.openai.com => api.domain.com
- Chrome内划词后可快捷键直接唤起开始翻译 
- 背景可自适应网页背景

**Comment by yetone** [comment]
都是很棒的建议！这些功能接下来都会加上，十分感谢！

**Comment by withuan** [comment]
感谢开发者所做的工作！

**Comment by xuandao** [comment]
复议～～我也需要

**Comment by celery94** [comment]
api地址自定义 太需要了

**Comment by yetone** [comment]
已支持自定义 API URL，请升级到最新版本

<img width="438" alt="Screenshot 2023-03-07 at 12 27 40" src="https://user-images.githubusercontent.com/1206493/223320934-ec4e634d-3548-4a86-a000-66650ee933da.png">

**Comment by yic66d** [comment]
批准

**Comment by jiu90761** [comment]
已阅

**Comment by wu5c837** [comment]
同意

**Comment by radombb** [comment]
> * domain.com

请问api地址用这个domain就不需要翻墙吗？或者有什么替代的api地址可用吗

**Comment by radombb** [comment]
> * 建议API地址可自定义(照顾墙内) eg.  api.openai.com => api.domain.com
> * Chrome内划词后可快捷键直接唤起开始翻译
> * 背景可自适应网页背景

请问有什么不需要翻墙的api替代地址吗？

**Comment by jarlin8** [comment]
自己买个域名，或者是用freenom的免费域名，用服务器反带一下。
域名这个是必需的，没有境外服务器的，参考这个使用cloudflare的教程。[https://github.com/noobnooc/noobnooc/discussions/9](url)
还有个使用腾讯云函数的操作，自己网上找一下教程。

**Comment by yetone** [comment]
感谢反馈，已经支持
