### ISSUE TITLE
[Bug] {{安装后无法打开，仅图标闪现在任务栏}}

### ISSUE THREAD

**Issue by lifeclips** [yetone/openai-translator#623]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.37

### 系统/浏览器版本 System/Browser version

Windows 10 22H2 19045.2846

### 复现步骤 Reproduce step

下载[OpenAI.Translator_0.0.37_x64_en-US.msi](https://github.com/yetone/openai-translator/releases/download/v0.0.37/OpenAI.Translator_0.0.37_x64_en-US.msi)安装时选择Launch OpenAI Translator，或直接打开OpenAI Translator

### 你看到了什么错误？What errors do you see?

主界面未出现，图标出现在任务栏，鼠标经过一下就消失了

### 你期望看到什么？What did you expect to see?

正常运行

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by LJZ20** [comment]
我在windows安装了[OpenAI.Translator_0.3.32_x64_en-US.msi](https://github.com/openai-translator/openai-translator/releases/download/v0.3.32/OpenAI.Translator_0.3.32_x64_en-US.msi)，发现了同样的问题（根本无法正常运行，仅出现了图标）。请问您是怎么解决的呀？
