### ISSUE TITLE
[Bug] win11客户端无法打开，任务栏显示图标但不显示主窗口

### ISSUE THREAD

**Issue by douxy1994** [yetone/openai-translator#635]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.37

### 系统/浏览器版本 System/Browser version

windows 11 pro for workstations

### 复现步骤 Reproduce step

启动OT，只在任务栏显示图标，但桌面上不出现任何窗口。通过右下角托盘选择show也没有反应。任务栏图标点击无反应，鼠标悬停显示这个窗口。多次重新启动无法解决此问题。
![屏幕截图 2023-04-24 115956](https://user-images.githubusercontent.com/58248905/233898154-9b891424-5b49-4491-8a76-80b06f174fb9.png)

### 你看到了什么错误？What errors do you see?

无法启动。

### 你期望看到什么？What did you expect to see?

恢复正常。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by douxy1994** [comment]
截图无法上传？

**Comment by lwc8699793** [comment]
我的win10也会出现同样的问题，

**Comment by bravepig99** [comment]
出现同样问题

**Comment by XuNing2** [comment]
同样的问题

**Comment by tianlichunhong** [comment]
同样问题，主窗口根本打不开。0.37版本不行，0.36版本也不行。不知道缺少什么环境。

**Comment by oldboot** [comment]
1、卸载OpenAI Translator
2、 删除%USERPROFILE%\AppData\Local\xyz.yetone.apps.openai-translator    文件夹
      删除%USERPROFILE%\AppData\Roaming\xyz.yetone.apps.openai-translator   文件夹
3、重新安装：OpenAI.Translator_0.0.36_x64_en-US.msi  （安装完成，不要运行）
4、到安装目录下resources文件夹中把“get-selected-text.applescript”后缀  .applescript  改成   .js   改完因该是这个名字  get-selected-text.js（默认安装目录在此C:\Program Files\OpenAI Translator\resources）
注：修改文件后缀名，记得关闭 “隐藏已知文件扩展名” 选项 （该选项是Windows的设置）

**Comment by bravepig99** [comment]
> 1、卸载OpenAI Translator 2、 删除%USERPROFILE%\AppData\Local\xyz.yetone.apps.openai-translator 文件夹 删除%USERPROFILE%\AppData\Roaming\xyz.yetone.apps.openai-translator 文件夹 3、重新安装：OpenAI.Translator_0.0.36_x64_en-US.msi （安装完成，不要运行） 4、到安装目录下resources文件夹中把“get-selected-text.applescript”后缀 .applescript 改成 .js 改完因该是这个名字 get-selected-text.js（默认安装目录在此C:\Program Files\OpenAI Translator\resources） 注：修改文件后缀名，记得关闭 “隐藏已知文件扩展名” 选项 （该选项是Windows的设置）

根据这个操作，已经修复：））

**Comment by yetone** [comment]
十分抱歉带来了不好的体验，新版本已修复这个问题

**Comment by daysneco** [comment]
0.38安装之后无法启动，点击图标没有任何反应
