### ISSUE TITLE
希望能增加一个DeepL的c 的功能

### ISSUE THREAD

**Issue by petteran** [yetone/openai-translator#659]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

增加一个deepl 的RapidAPI 的选项

### 描述 Motivation

chat-gpt对网络环境要求过于高了,而且非专业人士不需要那么高的翻译质量,deepl 的反而稳定,之前用过大佬的bop 插件,deepl 往往是第一个出来,openai 慢还报错.
win版本没有好的解析deepl api 的软件,希望大佬出手.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by mrzeuscn** [comment]
**pot** 可以：[https://pot.pylogmon.cn/](url)

**Comment by petteran** [comment]
感谢大佬

**Comment by jt-wang** [comment]
@imshawin @petteran looks like the original `pot` link is broken now, and here's the new available link https://pot-app.com/
