### ISSUE TITLE
Please remove GA and sentry tracking, or provide an option to turn off tracking.

### ISSUE THREAD

**Issue by jim60105** [yetone/openai-translator#665]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

Please remove GA and sentry tracking, or provide an option to turn off tracking.

### 描述 Motivation

To protect user privacy, browser extensions that works on all domains should not send user inputs and any other tracking back to the server. Or at least there should be an option for the user to turn it off.

**Just imagine my shock when I notice I was being tracked on every web page in daily use.**

### Solution

Please remove GA and sentry tracking, or provide an option to turn off tracking.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
Sentry has done an excellent job in protecting privacy by not sending any user input to the server.

**Comment by jim60105** [comment]
I think you should not send any data to any server that is not related to the translation function, especially when I am not operating this tool.

If you must, please fix the promise here.
![image](https://user-images.githubusercontent.com/16995691/235799744-7360cedc-3bf8-40e2-8036-977a35d88771.png)

**Comment by yetone** [comment]
I just made a change to collect data only when it is in use: https://github.com/yetone/openai-translator/commit/cd394a26ecbd85542352aab38f59ad1b0a88e137

**Comment by jim60105** [comment]
Thank you for your attention and quick fix👍

**Comment by yetone** [comment]
And support disable collecting statistics now: https://github.com/yetone/openai-translator/commit/31dfa4262fec07e52eec64835cd204c00ace3004

**Comment by VoVAllen** [comment]
It doesn't make sense to inject gtag to any website users are visiting. I received CSP policy warning on the console. Will it collect my browser history also?

**Comment by JokerQyou** [comment]
The browser extension (specifically 0.1.15 in Chrome Web Store) would send replay data to Sentry server on errors, although it's not clear what accounts for an "error". URL of current page is included in the replay data. The request payload looks like this:

```json
{"event_id":"__SOME_UNIQUE_ID__","sent_at":"2023-05-07T00:48:39.123Z","sdk":{"name":"sentry.javascript.react","version":"7.49.0"}}
{"type":"event"}
{"exception":{"values":[{"type":"Error","value":"Extension context invalidated.","stacktrace":{"frames":[{"filename":"chrome-extension://ogjibjphoadhljaoicdnjnmgokohngcc/js/content_script.js","function":"o","in_app":true,"lineno":1,"colno":2090},{"filename":"<anonymous>","function":"Generator.next","in_app":true},{"filename":"chrome-extension://ogjibjphoadhljaoicdnjnmgokohngcc/js/content_script.js","function":"?","in_app":true,"lineno":20,"colno":2057}]},"mechanism":{"type":"onunhandledrejection","handled":false}}]},"level":"error","platform":"javascript","event_id":"__SOME_UNIQUE_ID__","timestamp":121213123232.112,"environment":"production","sdk":{"integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","Dedupe","HttpContext","BrowserTracing","Replay"],"name":"sentry.javascript.react","version":"7.49.0","packages":[{"name":"npm:@sentry/react","version":"7.49.0"}]},"breadcrumbs":[{"timestamp":121213123232.112,"category":"sentry.transaction","event_id":"__SOME_UNIQUE_ID__","message":"__SOME_HASH__"},{"timestamp":121213123232.112,"category":"ui.click","message":"td > div > span > a"},{"timestamp":121213123232.112,"category":"ui.click","message":"button.some_class[type=\"button\"]"}],"request":{"url":"https://URL/#EVEN_HASH_IS_INCLUDED","headers":{"User-Agent":"USER_AGENT"}}}
```

It contains 3 lines of individual JSON content, and in the last object there's the full page URL (includes the page hash, which is the part after the `#`, which is supposed to normally stay local and not send to backend server). Any ETA for the ability to disable Sentry error reporting and page tracking in browser extension?

**Comment by yetone** [comment]
@JokerQyou It's very wired, only the desktop app sends the sentry data now: https://github.com/yetone/openai-translator/blob/b698182f874fbb22b3416522b610f758bc546092/src/common/analysis.ts#L23

**Comment by JokerQyou** [comment]
> And I don't see anything about sentry in browser developer tools

I thought the replay data is only captured and sent after an error occurred.

Anyway I think I know what happened now. As you can see from the replay data in my previous comment, the error is `Extension context invalidated`. This commonly happens when a browser extension got updated (after which its injected content scripts would lose connection to the background script). So in this case I think the replay data might be sent by an older version of this extension. I've only seen it once, but the request data was lost already (after a browser update).
