### ISSUE TITLE
Add Vietnam to the whitelist, please

### ISSUE THREAD

**Issue by thuongtin** [yetone/openai-translator#668]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.4.1

### 系统/浏览器版本 System/Browser version

112.0.5615.137

### 复现步骤 Reproduce step

OpenAI has allowed users in Vietnam to use their service for some time now. I introduced this extension to my friends, but warning messages keep popping up constantly.

### 你看到了什么错误？What errors do you see?

IP Warning

### 你期望看到什么？What did you expect to see?

Add Vietnam to the whitelist

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
Vietnam is not in https://platform.openai.com/docs/supported-countries. Neither do I find any news that claims it has become available. Is the offical app accessible in Vietnam?

**Comment by thuongtin** [comment]
I am using both chat service and API. Everything is working normally.

**Comment by OverflowCat** [comment]
Okay, although I do not find the official statement. According to [[1]](https://tuoitrenews.vn/news/business/20230212/ai-chatbot-chatgpt-plus-available-in-vietnam/71482.html) [[2]](https://www.toponseek.com/blogs/chatgpt-plus/), I will make a pull request.

**Comment by OverflowCat** [comment]
Has been fixed in #691. Please close this issue 🚀
