### ISSUE TITLE
[Bug] {{打开软件每次都提示"OpenAl Translator" would like to control this computer using accessibility features.}}

### ISSUE THREAD

**Issue by yuluod** [yetone/openai-translator#671]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.41

### 系统/浏览器版本 System/Browser version

macOS 13.4 Beta

### 复现步骤 Reproduce step

安装之后直接打开

### 你看到了什么错误？What errors do you see?

提示需要权限，但是实际上已经给予了权限。
![bug](https://user-images.githubusercontent.com/9930784/236137682-cb691e1e-1e4e-46af-accf-d92b9c515435.jpeg)

### 你期望看到什么？What did you expect to see?

应该是能直接打开使用。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
你好，README 里有相关解决方案：https://github.com/yetone/openai-translator#troubleshooting

**Comment by exgbit** [comment]
给你个办法，在macos的系统设置->隐私与安全性->辅助功能中，找到Open Translator，先选中该项，点击下面的减号，删掉这个授权
然后再打开Open Translator，重新授权

**Comment by richsamer** [comment]
@yetone @exgbit 感谢，已经解决。

**Comment by yuluod** [comment]
> 你好，README 里有相关解决方案：https://github.com/yetone/openai-translator#troubleshooting

看到了，谢谢
