### ISSUE TITLE
[Bug] 多屏下用快捷键翻译不显示窗口

### ISSUE THREAD

**Issue by 276562578** [yetone/openai-translator#679]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.43

### 系统/浏览器版本 System/Browser version

win 10

### 复现步骤 Reproduce step

我是多屏窗口，三屏，当其中一个屏幕选中文字后用快捷键时，软件会消失，貌似是跑到莫名的位置

### 你看到了什么错误？What errors do you see?

窗口消失不见

### 你期望看到什么？What did you expect to see?

回到正常窗口内

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
这个问题已在最新版中修复，您可以测试一下

**Comment by 276562578** [comment]
已经修复了
