### ISSUE TITLE
Why not just collecting the mouse position on `mouseup` event? 

### ISSUE THREAD

**Issue by captain-martin** [yetone/openai-translator#7]
https://github.com/yetone/openai-translator/blob/1956b92c88252ab7107f7343cf050d16f8d4dfec/src/content/index.tsx#L138-L141

**Comment by yetone** [comment]
You make a lot of sense! Maybe I was too tired from coding all night and used such a stupid method. It's fixed now, just upgrade to the latest version. Thank you for letting me know!
