### ISSUE TITLE
[功能建议] 支持PDF文档划词翻译

### ISSUE THREAD

**Issue by dijingkai** [yetone/openai-translator#70]
试用了一下，发现使用 chatGPT 的翻译效果比之前用的 [沙拉查词](https://github.com/crimx/ext-saladict) 好很多。但使用过程中觉得在某些方面也可以借鉴一下沙拉查词，望考虑一下（太想把沙拉查词替换了，可惜不支持PDF划词翻译🤪）。
+ 支持浏览器内打开的 `PDF文档` 的划词翻译
+ 如 #25 所述，增加一个常驻界面的钉子功能
+ 引入 `i18n`，界面更加本地化，language 至少支持中文和英文 （当然，优先级不是那么高）

**Comment by szh-bash** [comment]
参考 #11 临时解决方案

**Comment by JDYG** [comment]
PDF划词翻译希望能处理好换行的问题。因为PDF中每次换行都有一个强制的换行符，复制到translator中后，句子是不连续的。
