### ISSUE TITLE
network request blocked by CSP on firefox

### ISSUE THREAD

**Issue by maltoze** [yetone/openai-translator#77]
currently, network request are being blocked on some websites when using firefox.

![CSP-error](https://user-images.githubusercontent.com/18044730/223623809-d6c6d1f8-21d3-427b-b846-de9d1ffb5cd7.png)

**Comment by selang** [comment]
In the latest version of Chrome, cross-domain access to the network is also prohibited. Is this injected into the page? You can try to send network requests in the background.

**Comment by maltoze** [comment]
https://discourse.mozilla.org/t/the-api-request-in-the-content-scripts-was-blocked-by-csp/111951

seems we need to move the api requests to the background.js

**Comment by maltoze** [comment]
> In the latest version of Chrome, cross-domain access to the network is also prohibited. Is this injected into the page? You can try to send network requests in the background.

Which version of Chrome are you using? I tried the latest version of Chrome (Version 111.0.5563.65 (Official Build) (64-bit)) and did not encounter this issue.
