### ISSUE TITLE
Extension Option点击了，输入api key的输入框没有显示

### ISSUE THREAD

**Issue by NTTAT-Shou-Chin** [yetone/openai-translator#8]

**Comment by YoleYu** [comment]
The same with me. And there isn't a place to input manually in Setting.

**Comment by yetone** [comment]
@NTTAT-Shou-Chin @YoleYu 

十分抱歉给你们带来了困扰，主要原因是我只做了 popup 页面（左键点击插件图标即可打开），没有做 options 页面（右键点击插件图标，在弹出菜单中点击 options 即可打开），我再最新版本 `v0.0.7` 中已经加入了 options 页面，更新一下就好了！十分感谢！
