### ISSUE TITLE
“You exceeded your current quota, please check your plan and billing details.”

### ISSUE THREAD

**Issue by RJdeck** [yetone/openai-translator#92]
使用插件时报错“You exceeded your current quota, please check your plan and billing details”，但是同一个账户能够正常使用chatGPT网页上的服务，并没有限制。

**Comment by RJdeck** [comment]
需要自己前往openai的账户设置中添加支付方式，然后更新api key。

**Comment by Scarhei** [comment]
请问如何添加支付方式呢
