### ISSUE TITLE
feature: grammar analyzer/explainer 语法解析

### ISSUE THREAD

**Issue by ytyt-yt** [yetone/openai-translator#93]
自用加了个语法解析的功能，方便外语学习者。

有需要的话我可以发 PR，或者可以参考[commit](https://github.com/ytyt-yt/openai-translator/commit/9f81a4e4dbe8d9a9d2b9f3745fe4068a013f7722)实现。功能可以参考下面截图。

另外发现些小问题，一个是 `fromChinese/toChinese` 判断应该是 `index >= 0` 而不是 `> 0`，另一个感觉 `assistantPrompt` 的 `role` 可能选 `user` 比较好（可参考官方文档示例，相当于是 user 来指示 assistant），不过实际影响不大。

<img width="600" alt="1" src="https://user-images.githubusercontent.com/20288519/223707231-901fdea8-bfec-4745-9cd1-f488cab59b41.png">
<img width="600" alt="2" src="https://user-images.githubusercontent.com/20288519/223707378-cb892c81-f281-486e-83d4-873e3d9fa9af.png">
<img width="600" alt="3" src="https://user-images.githubusercontent.com/20288519/223707368-78551e8c-3373-4849-a54a-ff7378c8650e.png">

**Comment by HJianBo** [comment]
正想来开 Feature Request，没想到已经提出来了！希望可以合并！感谢各位大佬

**Comment by FmoX** [comment]
作者可能来不及回复 可以发这个功能的成品吗 很需要这个功能

**Comment by ytyt-yt** [comment]
@FmoX @HJianBo Merged, should be enabled in the next release. :)
