### ISSUE TITLE
使用了一会就收到了禁用的邮件，大家有遇到这种问题吗？

### ISSUE THREAD

**Issue by dforel** [yetone/openai-translator#98]
---------------------------------------
Hi there,

After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.

Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our content policy, repeated attempts at disallowed use-cases, or accessing the API from an unsupported location. You may also wish to review our Terms of Use.

If you believe this is in error and would like to appeal, please contact us through our help center. We will review appeals within one business day and will contact you if we reinstate access to the API.

Best,
The OpenAI team
-----------------------------------------

刚刚就在拿openai的文档尝试翻译一下而已，然后就用不了了。

**Comment by szh-bash** [comment]
可能需要支持自定义 organization-id ?

**Comment by Octopuszz** [comment]
我也是直接使用api，插件直接报错
Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.

**Comment by qi7f0d4** [comment]
i think so

**Comment by san3b64** [comment]
i think so

**Comment by shiyic5b0** [comment]
i think so

**Comment by crosspacific** [comment]
**风向旗参考快讯**

OpenAI开始大量封API，被封后会收到邮件提示：常见的违规原因包括违反我们的内容政策，反复尝试不允许的使用情况，或从不支持的地点访问API。
一些自建应用会购买大量ChatGPT的号，利用有赠金的KEY进行轮询。

**Comment by Lxb921006** [comment]
Me too. I was banned after only one test

**Comment by dforel** [comment]
我关闭这条内容了，大概率是openai那边的严格处理问题。

**Comment by jjqtony** [comment]
> 
Me too.  I was banned after only one test.

**Comment by Tian1556** [comment]
我也是，怎么能申请恢复呢

**Comment by SummerChaser** [comment]
我也是用了一次被封了

**Comment by Sarah20187** [comment]
Same here

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![WX20230401-184113@2x](https://user-images.githubusercontent.com/50973253/229283420-c3f6cb09-06d3-4fc2-a469-affc14098fb5.png)
现在群聊接近二百人了，如果不能进群，请加微信AI-camp-666，然后拉进群
